// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: white_board.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_white_5fboard_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_white_5fboard_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_white_5fboard_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_white_5fboard_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_white_5fboard_2eproto;
namespace whiteboard {
class DrawOperateData;
struct DrawOperateDataDefaultTypeInternal;
extern DrawOperateDataDefaultTypeInternal _DrawOperateData_default_instance_;
class MessageHeader;
struct MessageHeaderDefaultTypeInternal;
extern MessageHeaderDefaultTypeInternal _MessageHeader_default_instance_;
class MessageMeta;
struct MessageMetaDefaultTypeInternal;
extern MessageMetaDefaultTypeInternal _MessageMeta_default_instance_;
class RoomOperateData;
struct RoomOperateDataDefaultTypeInternal;
extern RoomOperateDataDefaultTypeInternal _RoomOperateData_default_instance_;
class WhiteboardMessage;
struct WhiteboardMessageDefaultTypeInternal;
extern WhiteboardMessageDefaultTypeInternal _WhiteboardMessage_default_instance_;
}  // namespace whiteboard
PROTOBUF_NAMESPACE_OPEN
template<> ::whiteboard::DrawOperateData* Arena::CreateMaybeMessage<::whiteboard::DrawOperateData>(Arena*);
template<> ::whiteboard::MessageHeader* Arena::CreateMaybeMessage<::whiteboard::MessageHeader>(Arena*);
template<> ::whiteboard::MessageMeta* Arena::CreateMaybeMessage<::whiteboard::MessageMeta>(Arena*);
template<> ::whiteboard::RoomOperateData* Arena::CreateMaybeMessage<::whiteboard::RoomOperateData>(Arena*);
template<> ::whiteboard::WhiteboardMessage* Arena::CreateMaybeMessage<::whiteboard::WhiteboardMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace whiteboard {

enum OperateType : int {
  OPERATE_TYPE_UNKNOWN = 0,
  OPERATE_TYPE_ROOM = 1,
  OPERATE_TYPE_DRAW = 2,
  OperateType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  OperateType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool OperateType_IsValid(int value);
constexpr OperateType OperateType_MIN = OPERATE_TYPE_UNKNOWN;
constexpr OperateType OperateType_MAX = OPERATE_TYPE_DRAW;
constexpr int OperateType_ARRAYSIZE = OperateType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* OperateType_descriptor();
template<typename T>
inline const std::string& OperateType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, OperateType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function OperateType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    OperateType_descriptor(), enum_t_value);
}
inline bool OperateType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, OperateType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<OperateType>(
    OperateType_descriptor(), name, value);
}
enum OperateId : int {
  OPERATE_ID_UNKNOWN = 0,
  ROOM_CREATE = 101,
  ROOM_JOIN = 102,
  ROOM_EXIT = 103,
  ROOM_KICK = 104,
  DRAW_LINE = 201,
  DRAW_CIRCLE = 202,
  DRAW_RECT = 203,
  DRAW_ERASE = 204,
  DRAW_MOVE = 205,
  OperateId_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  OperateId_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool OperateId_IsValid(int value);
constexpr OperateId OperateId_MIN = OPERATE_ID_UNKNOWN;
constexpr OperateId OperateId_MAX = DRAW_MOVE;
constexpr int OperateId_ARRAYSIZE = OperateId_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* OperateId_descriptor();
template<typename T>
inline const std::string& OperateId_Name(T enum_t_value) {
  static_assert(::std::is_same<T, OperateId>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function OperateId_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    OperateId_descriptor(), enum_t_value);
}
inline bool OperateId_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, OperateId* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<OperateId>(
    OperateId_descriptor(), name, value);
}
// ===================================================================

class MessageHeader final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:whiteboard.MessageHeader) */ {
 public:
  inline MessageHeader() : MessageHeader(nullptr) {}
  ~MessageHeader() override;
  explicit PROTOBUF_CONSTEXPR MessageHeader(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MessageHeader(const MessageHeader& from);
  MessageHeader(MessageHeader&& from) noexcept
    : MessageHeader() {
    *this = ::std::move(from);
  }

  inline MessageHeader& operator=(const MessageHeader& from) {
    CopyFrom(from);
    return *this;
  }
  inline MessageHeader& operator=(MessageHeader&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MessageHeader& default_instance() {
    return *internal_default_instance();
  }
  static inline const MessageHeader* internal_default_instance() {
    return reinterpret_cast<const MessageHeader*>(
               &_MessageHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MessageHeader& a, MessageHeader& b) {
    a.Swap(&b);
  }
  inline void Swap(MessageHeader* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MessageHeader* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MessageHeader* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MessageHeader>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MessageHeader& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MessageHeader& from) {
    MessageHeader::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MessageHeader* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "whiteboard.MessageHeader";
  }
  protected:
  explicit MessageHeader(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVersionFieldNumber = 3,
    kMsgIdFieldNumber = 1,
    kTimestampFieldNumber = 2,
  };
  // string version = 3;
  void clear_version();
  const std::string& version() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_version(ArgT0&& arg0, ArgT... args);
  std::string* mutable_version();
  PROTOBUF_NODISCARD std::string* release_version();
  void set_allocated_version(std::string* version);
  private:
  const std::string& _internal_version() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_version(const std::string& value);
  std::string* _internal_mutable_version();
  public:

  // uint64 msg_id = 1;
  void clear_msg_id();
  uint64_t msg_id() const;
  void set_msg_id(uint64_t value);
  private:
  uint64_t _internal_msg_id() const;
  void _internal_set_msg_id(uint64_t value);
  public:

  // uint64 timestamp = 2;
  void clear_timestamp();
  uint64_t timestamp() const;
  void set_timestamp(uint64_t value);
  private:
  uint64_t _internal_timestamp() const;
  void _internal_set_timestamp(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:whiteboard.MessageHeader)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr version_;
    uint64_t msg_id_;
    uint64_t timestamp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_white_5fboard_2eproto;
};
// -------------------------------------------------------------------

class MessageMeta final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:whiteboard.MessageMeta) */ {
 public:
  inline MessageMeta() : MessageMeta(nullptr) {}
  ~MessageMeta() override;
  explicit PROTOBUF_CONSTEXPR MessageMeta(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MessageMeta(const MessageMeta& from);
  MessageMeta(MessageMeta&& from) noexcept
    : MessageMeta() {
    *this = ::std::move(from);
  }

  inline MessageMeta& operator=(const MessageMeta& from) {
    CopyFrom(from);
    return *this;
  }
  inline MessageMeta& operator=(MessageMeta&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MessageMeta& default_instance() {
    return *internal_default_instance();
  }
  static inline const MessageMeta* internal_default_instance() {
    return reinterpret_cast<const MessageMeta*>(
               &_MessageMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(MessageMeta& a, MessageMeta& b) {
    a.Swap(&b);
  }
  inline void Swap(MessageMeta* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MessageMeta* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MessageMeta* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MessageMeta>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MessageMeta& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MessageMeta& from) {
    MessageMeta::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MessageMeta* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "whiteboard.MessageMeta";
  }
  protected:
  explicit MessageMeta(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserIdFieldNumber = 1,
    kRoomIdFieldNumber = 2,
    kOperateTypeFieldNumber = 3,
    kOperateIdFieldNumber = 4,
  };
  // uint64 user_id = 1;
  void clear_user_id();
  uint64_t user_id() const;
  void set_user_id(uint64_t value);
  private:
  uint64_t _internal_user_id() const;
  void _internal_set_user_id(uint64_t value);
  public:

  // uint64 room_id = 2;
  void clear_room_id();
  uint64_t room_id() const;
  void set_room_id(uint64_t value);
  private:
  uint64_t _internal_room_id() const;
  void _internal_set_room_id(uint64_t value);
  public:

  // .whiteboard.OperateType operate_type = 3;
  void clear_operate_type();
  ::whiteboard::OperateType operate_type() const;
  void set_operate_type(::whiteboard::OperateType value);
  private:
  ::whiteboard::OperateType _internal_operate_type() const;
  void _internal_set_operate_type(::whiteboard::OperateType value);
  public:

  // .whiteboard.OperateId operate_id = 4;
  void clear_operate_id();
  ::whiteboard::OperateId operate_id() const;
  void set_operate_id(::whiteboard::OperateId value);
  private:
  ::whiteboard::OperateId _internal_operate_id() const;
  void _internal_set_operate_id(::whiteboard::OperateId value);
  public:

  // @@protoc_insertion_point(class_scope:whiteboard.MessageMeta)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t user_id_;
    uint64_t room_id_;
    int operate_type_;
    int operate_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_white_5fboard_2eproto;
};
// -------------------------------------------------------------------

class RoomOperateData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:whiteboard.RoomOperateData) */ {
 public:
  inline RoomOperateData() : RoomOperateData(nullptr) {}
  ~RoomOperateData() override;
  explicit PROTOBUF_CONSTEXPR RoomOperateData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RoomOperateData(const RoomOperateData& from);
  RoomOperateData(RoomOperateData&& from) noexcept
    : RoomOperateData() {
    *this = ::std::move(from);
  }

  inline RoomOperateData& operator=(const RoomOperateData& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoomOperateData& operator=(RoomOperateData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoomOperateData& default_instance() {
    return *internal_default_instance();
  }
  static inline const RoomOperateData* internal_default_instance() {
    return reinterpret_cast<const RoomOperateData*>(
               &_RoomOperateData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(RoomOperateData& a, RoomOperateData& b) {
    a.Swap(&b);
  }
  inline void Swap(RoomOperateData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoomOperateData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoomOperateData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RoomOperateData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RoomOperateData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RoomOperateData& from) {
    RoomOperateData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoomOperateData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "whiteboard.RoomOperateData";
  }
  protected:
  explicit RoomOperateData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRoomNameFieldNumber = 1,
    kPasswordFieldNumber = 3,
    kUserNicknameFieldNumber = 4,
    kReasonFieldNumber = 5,
    kTargetUserIdFieldNumber = 6,
    kMaxUsersFieldNumber = 2,
  };
  // string room_name = 1;
  void clear_room_name();
  const std::string& room_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_room_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_room_name();
  PROTOBUF_NODISCARD std::string* release_room_name();
  void set_allocated_room_name(std::string* room_name);
  private:
  const std::string& _internal_room_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_room_name(const std::string& value);
  std::string* _internal_mutable_room_name();
  public:

  // string password = 3;
  void clear_password();
  const std::string& password() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_password(ArgT0&& arg0, ArgT... args);
  std::string* mutable_password();
  PROTOBUF_NODISCARD std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // string user_nickname = 4;
  void clear_user_nickname();
  const std::string& user_nickname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_user_nickname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_user_nickname();
  PROTOBUF_NODISCARD std::string* release_user_nickname();
  void set_allocated_user_nickname(std::string* user_nickname);
  private:
  const std::string& _internal_user_nickname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_user_nickname(const std::string& value);
  std::string* _internal_mutable_user_nickname();
  public:

  // string reason = 5;
  void clear_reason();
  const std::string& reason() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_reason(ArgT0&& arg0, ArgT... args);
  std::string* mutable_reason();
  PROTOBUF_NODISCARD std::string* release_reason();
  void set_allocated_reason(std::string* reason);
  private:
  const std::string& _internal_reason() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_reason(const std::string& value);
  std::string* _internal_mutable_reason();
  public:

  // uint64 target_user_id = 6;
  void clear_target_user_id();
  uint64_t target_user_id() const;
  void set_target_user_id(uint64_t value);
  private:
  uint64_t _internal_target_user_id() const;
  void _internal_set_target_user_id(uint64_t value);
  public:

  // uint32 max_users = 2;
  void clear_max_users();
  uint32_t max_users() const;
  void set_max_users(uint32_t value);
  private:
  uint32_t _internal_max_users() const;
  void _internal_set_max_users(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:whiteboard.RoomOperateData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr room_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_nickname_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr reason_;
    uint64_t target_user_id_;
    uint32_t max_users_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_white_5fboard_2eproto;
};
// -------------------------------------------------------------------

class DrawOperateData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:whiteboard.DrawOperateData) */ {
 public:
  inline DrawOperateData() : DrawOperateData(nullptr) {}
  ~DrawOperateData() override;
  explicit PROTOBUF_CONSTEXPR DrawOperateData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DrawOperateData(const DrawOperateData& from);
  DrawOperateData(DrawOperateData&& from) noexcept
    : DrawOperateData() {
    *this = ::std::move(from);
  }

  inline DrawOperateData& operator=(const DrawOperateData& from) {
    CopyFrom(from);
    return *this;
  }
  inline DrawOperateData& operator=(DrawOperateData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DrawOperateData& default_instance() {
    return *internal_default_instance();
  }
  static inline const DrawOperateData* internal_default_instance() {
    return reinterpret_cast<const DrawOperateData*>(
               &_DrawOperateData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(DrawOperateData& a, DrawOperateData& b) {
    a.Swap(&b);
  }
  inline void Swap(DrawOperateData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DrawOperateData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DrawOperateData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DrawOperateData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DrawOperateData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DrawOperateData& from) {
    DrawOperateData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DrawOperateData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "whiteboard.DrawOperateData";
  }
  protected:
  explicit DrawOperateData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kColorFieldNumber = 1,
    kLineWidthFieldNumber = 2,
    kStartXFieldNumber = 3,
    kStartYFieldNumber = 4,
    kEndXFieldNumber = 5,
    kEndYFieldNumber = 6,
    kCenterXFieldNumber = 7,
    kCenterYFieldNumber = 8,
    kRadiusFieldNumber = 9,
    kFillFieldNumber = 10,
    kLeftXFieldNumber = 11,
    kTopYFieldNumber = 12,
    kWidthFieldNumber = 13,
    kShapeIdFieldNumber = 15,
    kHeightFieldNumber = 14,
    kOffsetXFieldNumber = 16,
    kOffsetYFieldNumber = 17,
  };
  // string color = 1;
  void clear_color();
  const std::string& color() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_color(ArgT0&& arg0, ArgT... args);
  std::string* mutable_color();
  PROTOBUF_NODISCARD std::string* release_color();
  void set_allocated_color(std::string* color);
  private:
  const std::string& _internal_color() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_color(const std::string& value);
  std::string* _internal_mutable_color();
  public:

  // float line_width = 2;
  void clear_line_width();
  float line_width() const;
  void set_line_width(float value);
  private:
  float _internal_line_width() const;
  void _internal_set_line_width(float value);
  public:

  // float start_x = 3;
  void clear_start_x();
  float start_x() const;
  void set_start_x(float value);
  private:
  float _internal_start_x() const;
  void _internal_set_start_x(float value);
  public:

  // float start_y = 4;
  void clear_start_y();
  float start_y() const;
  void set_start_y(float value);
  private:
  float _internal_start_y() const;
  void _internal_set_start_y(float value);
  public:

  // float end_x = 5;
  void clear_end_x();
  float end_x() const;
  void set_end_x(float value);
  private:
  float _internal_end_x() const;
  void _internal_set_end_x(float value);
  public:

  // float end_y = 6;
  void clear_end_y();
  float end_y() const;
  void set_end_y(float value);
  private:
  float _internal_end_y() const;
  void _internal_set_end_y(float value);
  public:

  // float center_x = 7;
  void clear_center_x();
  float center_x() const;
  void set_center_x(float value);
  private:
  float _internal_center_x() const;
  void _internal_set_center_x(float value);
  public:

  // float center_y = 8;
  void clear_center_y();
  float center_y() const;
  void set_center_y(float value);
  private:
  float _internal_center_y() const;
  void _internal_set_center_y(float value);
  public:

  // float radius = 9;
  void clear_radius();
  float radius() const;
  void set_radius(float value);
  private:
  float _internal_radius() const;
  void _internal_set_radius(float value);
  public:

  // bool fill = 10;
  void clear_fill();
  bool fill() const;
  void set_fill(bool value);
  private:
  bool _internal_fill() const;
  void _internal_set_fill(bool value);
  public:

  // float left_x = 11;
  void clear_left_x();
  float left_x() const;
  void set_left_x(float value);
  private:
  float _internal_left_x() const;
  void _internal_set_left_x(float value);
  public:

  // float top_y = 12;
  void clear_top_y();
  float top_y() const;
  void set_top_y(float value);
  private:
  float _internal_top_y() const;
  void _internal_set_top_y(float value);
  public:

  // float width = 13;
  void clear_width();
  float width() const;
  void set_width(float value);
  private:
  float _internal_width() const;
  void _internal_set_width(float value);
  public:

  // uint64 shape_id = 15;
  void clear_shape_id();
  uint64_t shape_id() const;
  void set_shape_id(uint64_t value);
  private:
  uint64_t _internal_shape_id() const;
  void _internal_set_shape_id(uint64_t value);
  public:

  // float height = 14;
  void clear_height();
  float height() const;
  void set_height(float value);
  private:
  float _internal_height() const;
  void _internal_set_height(float value);
  public:

  // float offset_x = 16;
  void clear_offset_x();
  float offset_x() const;
  void set_offset_x(float value);
  private:
  float _internal_offset_x() const;
  void _internal_set_offset_x(float value);
  public:

  // float offset_y = 17;
  void clear_offset_y();
  float offset_y() const;
  void set_offset_y(float value);
  private:
  float _internal_offset_y() const;
  void _internal_set_offset_y(float value);
  public:

  // @@protoc_insertion_point(class_scope:whiteboard.DrawOperateData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr color_;
    float line_width_;
    float start_x_;
    float start_y_;
    float end_x_;
    float end_y_;
    float center_x_;
    float center_y_;
    float radius_;
    bool fill_;
    float left_x_;
    float top_y_;
    float width_;
    uint64_t shape_id_;
    float height_;
    float offset_x_;
    float offset_y_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_white_5fboard_2eproto;
};
// -------------------------------------------------------------------

class WhiteboardMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:whiteboard.WhiteboardMessage) */ {
 public:
  inline WhiteboardMessage() : WhiteboardMessage(nullptr) {}
  ~WhiteboardMessage() override;
  explicit PROTOBUF_CONSTEXPR WhiteboardMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  WhiteboardMessage(const WhiteboardMessage& from);
  WhiteboardMessage(WhiteboardMessage&& from) noexcept
    : WhiteboardMessage() {
    *this = ::std::move(from);
  }

  inline WhiteboardMessage& operator=(const WhiteboardMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline WhiteboardMessage& operator=(WhiteboardMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WhiteboardMessage& default_instance() {
    return *internal_default_instance();
  }
  enum DataCase {
    kRoomData = 3,
    kDrawData = 4,
    DATA_NOT_SET = 0,
  };

  static inline const WhiteboardMessage* internal_default_instance() {
    return reinterpret_cast<const WhiteboardMessage*>(
               &_WhiteboardMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(WhiteboardMessage& a, WhiteboardMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(WhiteboardMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WhiteboardMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  WhiteboardMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<WhiteboardMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const WhiteboardMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const WhiteboardMessage& from) {
    WhiteboardMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WhiteboardMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "whiteboard.WhiteboardMessage";
  }
  protected:
  explicit WhiteboardMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeaderFieldNumber = 1,
    kMetaFieldNumber = 2,
    kRoomDataFieldNumber = 3,
    kDrawDataFieldNumber = 4,
  };
  // .whiteboard.MessageHeader header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::whiteboard::MessageHeader& header() const;
  PROTOBUF_NODISCARD ::whiteboard::MessageHeader* release_header();
  ::whiteboard::MessageHeader* mutable_header();
  void set_allocated_header(::whiteboard::MessageHeader* header);
  private:
  const ::whiteboard::MessageHeader& _internal_header() const;
  ::whiteboard::MessageHeader* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::whiteboard::MessageHeader* header);
  ::whiteboard::MessageHeader* unsafe_arena_release_header();

  // .whiteboard.MessageMeta meta = 2;
  bool has_meta() const;
  private:
  bool _internal_has_meta() const;
  public:
  void clear_meta();
  const ::whiteboard::MessageMeta& meta() const;
  PROTOBUF_NODISCARD ::whiteboard::MessageMeta* release_meta();
  ::whiteboard::MessageMeta* mutable_meta();
  void set_allocated_meta(::whiteboard::MessageMeta* meta);
  private:
  const ::whiteboard::MessageMeta& _internal_meta() const;
  ::whiteboard::MessageMeta* _internal_mutable_meta();
  public:
  void unsafe_arena_set_allocated_meta(
      ::whiteboard::MessageMeta* meta);
  ::whiteboard::MessageMeta* unsafe_arena_release_meta();

  // .whiteboard.RoomOperateData room_data = 3;
  bool has_room_data() const;
  private:
  bool _internal_has_room_data() const;
  public:
  void clear_room_data();
  const ::whiteboard::RoomOperateData& room_data() const;
  PROTOBUF_NODISCARD ::whiteboard::RoomOperateData* release_room_data();
  ::whiteboard::RoomOperateData* mutable_room_data();
  void set_allocated_room_data(::whiteboard::RoomOperateData* room_data);
  private:
  const ::whiteboard::RoomOperateData& _internal_room_data() const;
  ::whiteboard::RoomOperateData* _internal_mutable_room_data();
  public:
  void unsafe_arena_set_allocated_room_data(
      ::whiteboard::RoomOperateData* room_data);
  ::whiteboard::RoomOperateData* unsafe_arena_release_room_data();

  // .whiteboard.DrawOperateData draw_data = 4;
  bool has_draw_data() const;
  private:
  bool _internal_has_draw_data() const;
  public:
  void clear_draw_data();
  const ::whiteboard::DrawOperateData& draw_data() const;
  PROTOBUF_NODISCARD ::whiteboard::DrawOperateData* release_draw_data();
  ::whiteboard::DrawOperateData* mutable_draw_data();
  void set_allocated_draw_data(::whiteboard::DrawOperateData* draw_data);
  private:
  const ::whiteboard::DrawOperateData& _internal_draw_data() const;
  ::whiteboard::DrawOperateData* _internal_mutable_draw_data();
  public:
  void unsafe_arena_set_allocated_draw_data(
      ::whiteboard::DrawOperateData* draw_data);
  ::whiteboard::DrawOperateData* unsafe_arena_release_draw_data();

  void clear_data();
  DataCase data_case() const;
  // @@protoc_insertion_point(class_scope:whiteboard.WhiteboardMessage)
 private:
  class _Internal;
  void set_has_room_data();
  void set_has_draw_data();

  inline bool has_data() const;
  inline void clear_has_data();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::whiteboard::MessageHeader* header_;
    ::whiteboard::MessageMeta* meta_;
    union DataUnion {
      constexpr DataUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::whiteboard::RoomOperateData* room_data_;
      ::whiteboard::DrawOperateData* draw_data_;
    } data_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_white_5fboard_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MessageHeader

// uint64 msg_id = 1;
inline void MessageHeader::clear_msg_id() {
  _impl_.msg_id_ = uint64_t{0u};
}
inline uint64_t MessageHeader::_internal_msg_id() const {
  return _impl_.msg_id_;
}
inline uint64_t MessageHeader::msg_id() const {
  // @@protoc_insertion_point(field_get:whiteboard.MessageHeader.msg_id)
  return _internal_msg_id();
}
inline void MessageHeader::_internal_set_msg_id(uint64_t value) {
  
  _impl_.msg_id_ = value;
}
inline void MessageHeader::set_msg_id(uint64_t value) {
  _internal_set_msg_id(value);
  // @@protoc_insertion_point(field_set:whiteboard.MessageHeader.msg_id)
}

// uint64 timestamp = 2;
inline void MessageHeader::clear_timestamp() {
  _impl_.timestamp_ = uint64_t{0u};
}
inline uint64_t MessageHeader::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline uint64_t MessageHeader::timestamp() const {
  // @@protoc_insertion_point(field_get:whiteboard.MessageHeader.timestamp)
  return _internal_timestamp();
}
inline void MessageHeader::_internal_set_timestamp(uint64_t value) {
  
  _impl_.timestamp_ = value;
}
inline void MessageHeader::set_timestamp(uint64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:whiteboard.MessageHeader.timestamp)
}

// string version = 3;
inline void MessageHeader::clear_version() {
  _impl_.version_.ClearToEmpty();
}
inline const std::string& MessageHeader::version() const {
  // @@protoc_insertion_point(field_get:whiteboard.MessageHeader.version)
  return _internal_version();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MessageHeader::set_version(ArgT0&& arg0, ArgT... args) {
 
 _impl_.version_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:whiteboard.MessageHeader.version)
}
inline std::string* MessageHeader::mutable_version() {
  std::string* _s = _internal_mutable_version();
  // @@protoc_insertion_point(field_mutable:whiteboard.MessageHeader.version)
  return _s;
}
inline const std::string& MessageHeader::_internal_version() const {
  return _impl_.version_.Get();
}
inline void MessageHeader::_internal_set_version(const std::string& value) {
  
  _impl_.version_.Set(value, GetArenaForAllocation());
}
inline std::string* MessageHeader::_internal_mutable_version() {
  
  return _impl_.version_.Mutable(GetArenaForAllocation());
}
inline std::string* MessageHeader::release_version() {
  // @@protoc_insertion_point(field_release:whiteboard.MessageHeader.version)
  return _impl_.version_.Release();
}
inline void MessageHeader::set_allocated_version(std::string* version) {
  if (version != nullptr) {
    
  } else {
    
  }
  _impl_.version_.SetAllocated(version, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.version_.IsDefault()) {
    _impl_.version_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:whiteboard.MessageHeader.version)
}

// -------------------------------------------------------------------

// MessageMeta

// uint64 user_id = 1;
inline void MessageMeta::clear_user_id() {
  _impl_.user_id_ = uint64_t{0u};
}
inline uint64_t MessageMeta::_internal_user_id() const {
  return _impl_.user_id_;
}
inline uint64_t MessageMeta::user_id() const {
  // @@protoc_insertion_point(field_get:whiteboard.MessageMeta.user_id)
  return _internal_user_id();
}
inline void MessageMeta::_internal_set_user_id(uint64_t value) {
  
  _impl_.user_id_ = value;
}
inline void MessageMeta::set_user_id(uint64_t value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:whiteboard.MessageMeta.user_id)
}

// uint64 room_id = 2;
inline void MessageMeta::clear_room_id() {
  _impl_.room_id_ = uint64_t{0u};
}
inline uint64_t MessageMeta::_internal_room_id() const {
  return _impl_.room_id_;
}
inline uint64_t MessageMeta::room_id() const {
  // @@protoc_insertion_point(field_get:whiteboard.MessageMeta.room_id)
  return _internal_room_id();
}
inline void MessageMeta::_internal_set_room_id(uint64_t value) {
  
  _impl_.room_id_ = value;
}
inline void MessageMeta::set_room_id(uint64_t value) {
  _internal_set_room_id(value);
  // @@protoc_insertion_point(field_set:whiteboard.MessageMeta.room_id)
}

// .whiteboard.OperateType operate_type = 3;
inline void MessageMeta::clear_operate_type() {
  _impl_.operate_type_ = 0;
}
inline ::whiteboard::OperateType MessageMeta::_internal_operate_type() const {
  return static_cast< ::whiteboard::OperateType >(_impl_.operate_type_);
}
inline ::whiteboard::OperateType MessageMeta::operate_type() const {
  // @@protoc_insertion_point(field_get:whiteboard.MessageMeta.operate_type)
  return _internal_operate_type();
}
inline void MessageMeta::_internal_set_operate_type(::whiteboard::OperateType value) {
  
  _impl_.operate_type_ = value;
}
inline void MessageMeta::set_operate_type(::whiteboard::OperateType value) {
  _internal_set_operate_type(value);
  // @@protoc_insertion_point(field_set:whiteboard.MessageMeta.operate_type)
}

// .whiteboard.OperateId operate_id = 4;
inline void MessageMeta::clear_operate_id() {
  _impl_.operate_id_ = 0;
}
inline ::whiteboard::OperateId MessageMeta::_internal_operate_id() const {
  return static_cast< ::whiteboard::OperateId >(_impl_.operate_id_);
}
inline ::whiteboard::OperateId MessageMeta::operate_id() const {
  // @@protoc_insertion_point(field_get:whiteboard.MessageMeta.operate_id)
  return _internal_operate_id();
}
inline void MessageMeta::_internal_set_operate_id(::whiteboard::OperateId value) {
  
  _impl_.operate_id_ = value;
}
inline void MessageMeta::set_operate_id(::whiteboard::OperateId value) {
  _internal_set_operate_id(value);
  // @@protoc_insertion_point(field_set:whiteboard.MessageMeta.operate_id)
}

// -------------------------------------------------------------------

// RoomOperateData

// string room_name = 1;
inline void RoomOperateData::clear_room_name() {
  _impl_.room_name_.ClearToEmpty();
}
inline const std::string& RoomOperateData::room_name() const {
  // @@protoc_insertion_point(field_get:whiteboard.RoomOperateData.room_name)
  return _internal_room_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RoomOperateData::set_room_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.room_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:whiteboard.RoomOperateData.room_name)
}
inline std::string* RoomOperateData::mutable_room_name() {
  std::string* _s = _internal_mutable_room_name();
  // @@protoc_insertion_point(field_mutable:whiteboard.RoomOperateData.room_name)
  return _s;
}
inline const std::string& RoomOperateData::_internal_room_name() const {
  return _impl_.room_name_.Get();
}
inline void RoomOperateData::_internal_set_room_name(const std::string& value) {
  
  _impl_.room_name_.Set(value, GetArenaForAllocation());
}
inline std::string* RoomOperateData::_internal_mutable_room_name() {
  
  return _impl_.room_name_.Mutable(GetArenaForAllocation());
}
inline std::string* RoomOperateData::release_room_name() {
  // @@protoc_insertion_point(field_release:whiteboard.RoomOperateData.room_name)
  return _impl_.room_name_.Release();
}
inline void RoomOperateData::set_allocated_room_name(std::string* room_name) {
  if (room_name != nullptr) {
    
  } else {
    
  }
  _impl_.room_name_.SetAllocated(room_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.room_name_.IsDefault()) {
    _impl_.room_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:whiteboard.RoomOperateData.room_name)
}

// uint32 max_users = 2;
inline void RoomOperateData::clear_max_users() {
  _impl_.max_users_ = 0u;
}
inline uint32_t RoomOperateData::_internal_max_users() const {
  return _impl_.max_users_;
}
inline uint32_t RoomOperateData::max_users() const {
  // @@protoc_insertion_point(field_get:whiteboard.RoomOperateData.max_users)
  return _internal_max_users();
}
inline void RoomOperateData::_internal_set_max_users(uint32_t value) {
  
  _impl_.max_users_ = value;
}
inline void RoomOperateData::set_max_users(uint32_t value) {
  _internal_set_max_users(value);
  // @@protoc_insertion_point(field_set:whiteboard.RoomOperateData.max_users)
}

// string password = 3;
inline void RoomOperateData::clear_password() {
  _impl_.password_.ClearToEmpty();
}
inline const std::string& RoomOperateData::password() const {
  // @@protoc_insertion_point(field_get:whiteboard.RoomOperateData.password)
  return _internal_password();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RoomOperateData::set_password(ArgT0&& arg0, ArgT... args) {
 
 _impl_.password_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:whiteboard.RoomOperateData.password)
}
inline std::string* RoomOperateData::mutable_password() {
  std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:whiteboard.RoomOperateData.password)
  return _s;
}
inline const std::string& RoomOperateData::_internal_password() const {
  return _impl_.password_.Get();
}
inline void RoomOperateData::_internal_set_password(const std::string& value) {
  
  _impl_.password_.Set(value, GetArenaForAllocation());
}
inline std::string* RoomOperateData::_internal_mutable_password() {
  
  return _impl_.password_.Mutable(GetArenaForAllocation());
}
inline std::string* RoomOperateData::release_password() {
  // @@protoc_insertion_point(field_release:whiteboard.RoomOperateData.password)
  return _impl_.password_.Release();
}
inline void RoomOperateData::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  _impl_.password_.SetAllocated(password, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.password_.IsDefault()) {
    _impl_.password_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:whiteboard.RoomOperateData.password)
}

// string user_nickname = 4;
inline void RoomOperateData::clear_user_nickname() {
  _impl_.user_nickname_.ClearToEmpty();
}
inline const std::string& RoomOperateData::user_nickname() const {
  // @@protoc_insertion_point(field_get:whiteboard.RoomOperateData.user_nickname)
  return _internal_user_nickname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RoomOperateData::set_user_nickname(ArgT0&& arg0, ArgT... args) {
 
 _impl_.user_nickname_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:whiteboard.RoomOperateData.user_nickname)
}
inline std::string* RoomOperateData::mutable_user_nickname() {
  std::string* _s = _internal_mutable_user_nickname();
  // @@protoc_insertion_point(field_mutable:whiteboard.RoomOperateData.user_nickname)
  return _s;
}
inline const std::string& RoomOperateData::_internal_user_nickname() const {
  return _impl_.user_nickname_.Get();
}
inline void RoomOperateData::_internal_set_user_nickname(const std::string& value) {
  
  _impl_.user_nickname_.Set(value, GetArenaForAllocation());
}
inline std::string* RoomOperateData::_internal_mutable_user_nickname() {
  
  return _impl_.user_nickname_.Mutable(GetArenaForAllocation());
}
inline std::string* RoomOperateData::release_user_nickname() {
  // @@protoc_insertion_point(field_release:whiteboard.RoomOperateData.user_nickname)
  return _impl_.user_nickname_.Release();
}
inline void RoomOperateData::set_allocated_user_nickname(std::string* user_nickname) {
  if (user_nickname != nullptr) {
    
  } else {
    
  }
  _impl_.user_nickname_.SetAllocated(user_nickname, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.user_nickname_.IsDefault()) {
    _impl_.user_nickname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:whiteboard.RoomOperateData.user_nickname)
}

// string reason = 5;
inline void RoomOperateData::clear_reason() {
  _impl_.reason_.ClearToEmpty();
}
inline const std::string& RoomOperateData::reason() const {
  // @@protoc_insertion_point(field_get:whiteboard.RoomOperateData.reason)
  return _internal_reason();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RoomOperateData::set_reason(ArgT0&& arg0, ArgT... args) {
 
 _impl_.reason_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:whiteboard.RoomOperateData.reason)
}
inline std::string* RoomOperateData::mutable_reason() {
  std::string* _s = _internal_mutable_reason();
  // @@protoc_insertion_point(field_mutable:whiteboard.RoomOperateData.reason)
  return _s;
}
inline const std::string& RoomOperateData::_internal_reason() const {
  return _impl_.reason_.Get();
}
inline void RoomOperateData::_internal_set_reason(const std::string& value) {
  
  _impl_.reason_.Set(value, GetArenaForAllocation());
}
inline std::string* RoomOperateData::_internal_mutable_reason() {
  
  return _impl_.reason_.Mutable(GetArenaForAllocation());
}
inline std::string* RoomOperateData::release_reason() {
  // @@protoc_insertion_point(field_release:whiteboard.RoomOperateData.reason)
  return _impl_.reason_.Release();
}
inline void RoomOperateData::set_allocated_reason(std::string* reason) {
  if (reason != nullptr) {
    
  } else {
    
  }
  _impl_.reason_.SetAllocated(reason, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.reason_.IsDefault()) {
    _impl_.reason_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:whiteboard.RoomOperateData.reason)
}

// uint64 target_user_id = 6;
inline void RoomOperateData::clear_target_user_id() {
  _impl_.target_user_id_ = uint64_t{0u};
}
inline uint64_t RoomOperateData::_internal_target_user_id() const {
  return _impl_.target_user_id_;
}
inline uint64_t RoomOperateData::target_user_id() const {
  // @@protoc_insertion_point(field_get:whiteboard.RoomOperateData.target_user_id)
  return _internal_target_user_id();
}
inline void RoomOperateData::_internal_set_target_user_id(uint64_t value) {
  
  _impl_.target_user_id_ = value;
}
inline void RoomOperateData::set_target_user_id(uint64_t value) {
  _internal_set_target_user_id(value);
  // @@protoc_insertion_point(field_set:whiteboard.RoomOperateData.target_user_id)
}

// -------------------------------------------------------------------

// DrawOperateData

// string color = 1;
inline void DrawOperateData::clear_color() {
  _impl_.color_.ClearToEmpty();
}
inline const std::string& DrawOperateData::color() const {
  // @@protoc_insertion_point(field_get:whiteboard.DrawOperateData.color)
  return _internal_color();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DrawOperateData::set_color(ArgT0&& arg0, ArgT... args) {
 
 _impl_.color_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:whiteboard.DrawOperateData.color)
}
inline std::string* DrawOperateData::mutable_color() {
  std::string* _s = _internal_mutable_color();
  // @@protoc_insertion_point(field_mutable:whiteboard.DrawOperateData.color)
  return _s;
}
inline const std::string& DrawOperateData::_internal_color() const {
  return _impl_.color_.Get();
}
inline void DrawOperateData::_internal_set_color(const std::string& value) {
  
  _impl_.color_.Set(value, GetArenaForAllocation());
}
inline std::string* DrawOperateData::_internal_mutable_color() {
  
  return _impl_.color_.Mutable(GetArenaForAllocation());
}
inline std::string* DrawOperateData::release_color() {
  // @@protoc_insertion_point(field_release:whiteboard.DrawOperateData.color)
  return _impl_.color_.Release();
}
inline void DrawOperateData::set_allocated_color(std::string* color) {
  if (color != nullptr) {
    
  } else {
    
  }
  _impl_.color_.SetAllocated(color, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.color_.IsDefault()) {
    _impl_.color_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:whiteboard.DrawOperateData.color)
}

// float line_width = 2;
inline void DrawOperateData::clear_line_width() {
  _impl_.line_width_ = 0;
}
inline float DrawOperateData::_internal_line_width() const {
  return _impl_.line_width_;
}
inline float DrawOperateData::line_width() const {
  // @@protoc_insertion_point(field_get:whiteboard.DrawOperateData.line_width)
  return _internal_line_width();
}
inline void DrawOperateData::_internal_set_line_width(float value) {
  
  _impl_.line_width_ = value;
}
inline void DrawOperateData::set_line_width(float value) {
  _internal_set_line_width(value);
  // @@protoc_insertion_point(field_set:whiteboard.DrawOperateData.line_width)
}

// float start_x = 3;
inline void DrawOperateData::clear_start_x() {
  _impl_.start_x_ = 0;
}
inline float DrawOperateData::_internal_start_x() const {
  return _impl_.start_x_;
}
inline float DrawOperateData::start_x() const {
  // @@protoc_insertion_point(field_get:whiteboard.DrawOperateData.start_x)
  return _internal_start_x();
}
inline void DrawOperateData::_internal_set_start_x(float value) {
  
  _impl_.start_x_ = value;
}
inline void DrawOperateData::set_start_x(float value) {
  _internal_set_start_x(value);
  // @@protoc_insertion_point(field_set:whiteboard.DrawOperateData.start_x)
}

// float start_y = 4;
inline void DrawOperateData::clear_start_y() {
  _impl_.start_y_ = 0;
}
inline float DrawOperateData::_internal_start_y() const {
  return _impl_.start_y_;
}
inline float DrawOperateData::start_y() const {
  // @@protoc_insertion_point(field_get:whiteboard.DrawOperateData.start_y)
  return _internal_start_y();
}
inline void DrawOperateData::_internal_set_start_y(float value) {
  
  _impl_.start_y_ = value;
}
inline void DrawOperateData::set_start_y(float value) {
  _internal_set_start_y(value);
  // @@protoc_insertion_point(field_set:whiteboard.DrawOperateData.start_y)
}

// float end_x = 5;
inline void DrawOperateData::clear_end_x() {
  _impl_.end_x_ = 0;
}
inline float DrawOperateData::_internal_end_x() const {
  return _impl_.end_x_;
}
inline float DrawOperateData::end_x() const {
  // @@protoc_insertion_point(field_get:whiteboard.DrawOperateData.end_x)
  return _internal_end_x();
}
inline void DrawOperateData::_internal_set_end_x(float value) {
  
  _impl_.end_x_ = value;
}
inline void DrawOperateData::set_end_x(float value) {
  _internal_set_end_x(value);
  // @@protoc_insertion_point(field_set:whiteboard.DrawOperateData.end_x)
}

// float end_y = 6;
inline void DrawOperateData::clear_end_y() {
  _impl_.end_y_ = 0;
}
inline float DrawOperateData::_internal_end_y() const {
  return _impl_.end_y_;
}
inline float DrawOperateData::end_y() const {
  // @@protoc_insertion_point(field_get:whiteboard.DrawOperateData.end_y)
  return _internal_end_y();
}
inline void DrawOperateData::_internal_set_end_y(float value) {
  
  _impl_.end_y_ = value;
}
inline void DrawOperateData::set_end_y(float value) {
  _internal_set_end_y(value);
  // @@protoc_insertion_point(field_set:whiteboard.DrawOperateData.end_y)
}

// float center_x = 7;
inline void DrawOperateData::clear_center_x() {
  _impl_.center_x_ = 0;
}
inline float DrawOperateData::_internal_center_x() const {
  return _impl_.center_x_;
}
inline float DrawOperateData::center_x() const {
  // @@protoc_insertion_point(field_get:whiteboard.DrawOperateData.center_x)
  return _internal_center_x();
}
inline void DrawOperateData::_internal_set_center_x(float value) {
  
  _impl_.center_x_ = value;
}
inline void DrawOperateData::set_center_x(float value) {
  _internal_set_center_x(value);
  // @@protoc_insertion_point(field_set:whiteboard.DrawOperateData.center_x)
}

// float center_y = 8;
inline void DrawOperateData::clear_center_y() {
  _impl_.center_y_ = 0;
}
inline float DrawOperateData::_internal_center_y() const {
  return _impl_.center_y_;
}
inline float DrawOperateData::center_y() const {
  // @@protoc_insertion_point(field_get:whiteboard.DrawOperateData.center_y)
  return _internal_center_y();
}
inline void DrawOperateData::_internal_set_center_y(float value) {
  
  _impl_.center_y_ = value;
}
inline void DrawOperateData::set_center_y(float value) {
  _internal_set_center_y(value);
  // @@protoc_insertion_point(field_set:whiteboard.DrawOperateData.center_y)
}

// float radius = 9;
inline void DrawOperateData::clear_radius() {
  _impl_.radius_ = 0;
}
inline float DrawOperateData::_internal_radius() const {
  return _impl_.radius_;
}
inline float DrawOperateData::radius() const {
  // @@protoc_insertion_point(field_get:whiteboard.DrawOperateData.radius)
  return _internal_radius();
}
inline void DrawOperateData::_internal_set_radius(float value) {
  
  _impl_.radius_ = value;
}
inline void DrawOperateData::set_radius(float value) {
  _internal_set_radius(value);
  // @@protoc_insertion_point(field_set:whiteboard.DrawOperateData.radius)
}

// bool fill = 10;
inline void DrawOperateData::clear_fill() {
  _impl_.fill_ = false;
}
inline bool DrawOperateData::_internal_fill() const {
  return _impl_.fill_;
}
inline bool DrawOperateData::fill() const {
  // @@protoc_insertion_point(field_get:whiteboard.DrawOperateData.fill)
  return _internal_fill();
}
inline void DrawOperateData::_internal_set_fill(bool value) {
  
  _impl_.fill_ = value;
}
inline void DrawOperateData::set_fill(bool value) {
  _internal_set_fill(value);
  // @@protoc_insertion_point(field_set:whiteboard.DrawOperateData.fill)
}

// float left_x = 11;
inline void DrawOperateData::clear_left_x() {
  _impl_.left_x_ = 0;
}
inline float DrawOperateData::_internal_left_x() const {
  return _impl_.left_x_;
}
inline float DrawOperateData::left_x() const {
  // @@protoc_insertion_point(field_get:whiteboard.DrawOperateData.left_x)
  return _internal_left_x();
}
inline void DrawOperateData::_internal_set_left_x(float value) {
  
  _impl_.left_x_ = value;
}
inline void DrawOperateData::set_left_x(float value) {
  _internal_set_left_x(value);
  // @@protoc_insertion_point(field_set:whiteboard.DrawOperateData.left_x)
}

// float top_y = 12;
inline void DrawOperateData::clear_top_y() {
  _impl_.top_y_ = 0;
}
inline float DrawOperateData::_internal_top_y() const {
  return _impl_.top_y_;
}
inline float DrawOperateData::top_y() const {
  // @@protoc_insertion_point(field_get:whiteboard.DrawOperateData.top_y)
  return _internal_top_y();
}
inline void DrawOperateData::_internal_set_top_y(float value) {
  
  _impl_.top_y_ = value;
}
inline void DrawOperateData::set_top_y(float value) {
  _internal_set_top_y(value);
  // @@protoc_insertion_point(field_set:whiteboard.DrawOperateData.top_y)
}

// float width = 13;
inline void DrawOperateData::clear_width() {
  _impl_.width_ = 0;
}
inline float DrawOperateData::_internal_width() const {
  return _impl_.width_;
}
inline float DrawOperateData::width() const {
  // @@protoc_insertion_point(field_get:whiteboard.DrawOperateData.width)
  return _internal_width();
}
inline void DrawOperateData::_internal_set_width(float value) {
  
  _impl_.width_ = value;
}
inline void DrawOperateData::set_width(float value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:whiteboard.DrawOperateData.width)
}

// float height = 14;
inline void DrawOperateData::clear_height() {
  _impl_.height_ = 0;
}
inline float DrawOperateData::_internal_height() const {
  return _impl_.height_;
}
inline float DrawOperateData::height() const {
  // @@protoc_insertion_point(field_get:whiteboard.DrawOperateData.height)
  return _internal_height();
}
inline void DrawOperateData::_internal_set_height(float value) {
  
  _impl_.height_ = value;
}
inline void DrawOperateData::set_height(float value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:whiteboard.DrawOperateData.height)
}

// uint64 shape_id = 15;
inline void DrawOperateData::clear_shape_id() {
  _impl_.shape_id_ = uint64_t{0u};
}
inline uint64_t DrawOperateData::_internal_shape_id() const {
  return _impl_.shape_id_;
}
inline uint64_t DrawOperateData::shape_id() const {
  // @@protoc_insertion_point(field_get:whiteboard.DrawOperateData.shape_id)
  return _internal_shape_id();
}
inline void DrawOperateData::_internal_set_shape_id(uint64_t value) {
  
  _impl_.shape_id_ = value;
}
inline void DrawOperateData::set_shape_id(uint64_t value) {
  _internal_set_shape_id(value);
  // @@protoc_insertion_point(field_set:whiteboard.DrawOperateData.shape_id)
}

// float offset_x = 16;
inline void DrawOperateData::clear_offset_x() {
  _impl_.offset_x_ = 0;
}
inline float DrawOperateData::_internal_offset_x() const {
  return _impl_.offset_x_;
}
inline float DrawOperateData::offset_x() const {
  // @@protoc_insertion_point(field_get:whiteboard.DrawOperateData.offset_x)
  return _internal_offset_x();
}
inline void DrawOperateData::_internal_set_offset_x(float value) {
  
  _impl_.offset_x_ = value;
}
inline void DrawOperateData::set_offset_x(float value) {
  _internal_set_offset_x(value);
  // @@protoc_insertion_point(field_set:whiteboard.DrawOperateData.offset_x)
}

// float offset_y = 17;
inline void DrawOperateData::clear_offset_y() {
  _impl_.offset_y_ = 0;
}
inline float DrawOperateData::_internal_offset_y() const {
  return _impl_.offset_y_;
}
inline float DrawOperateData::offset_y() const {
  // @@protoc_insertion_point(field_get:whiteboard.DrawOperateData.offset_y)
  return _internal_offset_y();
}
inline void DrawOperateData::_internal_set_offset_y(float value) {
  
  _impl_.offset_y_ = value;
}
inline void DrawOperateData::set_offset_y(float value) {
  _internal_set_offset_y(value);
  // @@protoc_insertion_point(field_set:whiteboard.DrawOperateData.offset_y)
}

// -------------------------------------------------------------------

// WhiteboardMessage

// .whiteboard.MessageHeader header = 1;
inline bool WhiteboardMessage::_internal_has_header() const {
  return this != internal_default_instance() && _impl_.header_ != nullptr;
}
inline bool WhiteboardMessage::has_header() const {
  return _internal_has_header();
}
inline void WhiteboardMessage::clear_header() {
  if (GetArenaForAllocation() == nullptr && _impl_.header_ != nullptr) {
    delete _impl_.header_;
  }
  _impl_.header_ = nullptr;
}
inline const ::whiteboard::MessageHeader& WhiteboardMessage::_internal_header() const {
  const ::whiteboard::MessageHeader* p = _impl_.header_;
  return p != nullptr ? *p : reinterpret_cast<const ::whiteboard::MessageHeader&>(
      ::whiteboard::_MessageHeader_default_instance_);
}
inline const ::whiteboard::MessageHeader& WhiteboardMessage::header() const {
  // @@protoc_insertion_point(field_get:whiteboard.WhiteboardMessage.header)
  return _internal_header();
}
inline void WhiteboardMessage::unsafe_arena_set_allocated_header(
    ::whiteboard::MessageHeader* header) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.header_);
  }
  _impl_.header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:whiteboard.WhiteboardMessage.header)
}
inline ::whiteboard::MessageHeader* WhiteboardMessage::release_header() {
  
  ::whiteboard::MessageHeader* temp = _impl_.header_;
  _impl_.header_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::whiteboard::MessageHeader* WhiteboardMessage::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:whiteboard.WhiteboardMessage.header)
  
  ::whiteboard::MessageHeader* temp = _impl_.header_;
  _impl_.header_ = nullptr;
  return temp;
}
inline ::whiteboard::MessageHeader* WhiteboardMessage::_internal_mutable_header() {
  
  if (_impl_.header_ == nullptr) {
    auto* p = CreateMaybeMessage<::whiteboard::MessageHeader>(GetArenaForAllocation());
    _impl_.header_ = p;
  }
  return _impl_.header_;
}
inline ::whiteboard::MessageHeader* WhiteboardMessage::mutable_header() {
  ::whiteboard::MessageHeader* _msg = _internal_mutable_header();
  // @@protoc_insertion_point(field_mutable:whiteboard.WhiteboardMessage.header)
  return _msg;
}
inline void WhiteboardMessage::set_allocated_header(::whiteboard::MessageHeader* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.header_;
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(header);
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.header_ = header;
  // @@protoc_insertion_point(field_set_allocated:whiteboard.WhiteboardMessage.header)
}

// .whiteboard.MessageMeta meta = 2;
inline bool WhiteboardMessage::_internal_has_meta() const {
  return this != internal_default_instance() && _impl_.meta_ != nullptr;
}
inline bool WhiteboardMessage::has_meta() const {
  return _internal_has_meta();
}
inline void WhiteboardMessage::clear_meta() {
  if (GetArenaForAllocation() == nullptr && _impl_.meta_ != nullptr) {
    delete _impl_.meta_;
  }
  _impl_.meta_ = nullptr;
}
inline const ::whiteboard::MessageMeta& WhiteboardMessage::_internal_meta() const {
  const ::whiteboard::MessageMeta* p = _impl_.meta_;
  return p != nullptr ? *p : reinterpret_cast<const ::whiteboard::MessageMeta&>(
      ::whiteboard::_MessageMeta_default_instance_);
}
inline const ::whiteboard::MessageMeta& WhiteboardMessage::meta() const {
  // @@protoc_insertion_point(field_get:whiteboard.WhiteboardMessage.meta)
  return _internal_meta();
}
inline void WhiteboardMessage::unsafe_arena_set_allocated_meta(
    ::whiteboard::MessageMeta* meta) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.meta_);
  }
  _impl_.meta_ = meta;
  if (meta) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:whiteboard.WhiteboardMessage.meta)
}
inline ::whiteboard::MessageMeta* WhiteboardMessage::release_meta() {
  
  ::whiteboard::MessageMeta* temp = _impl_.meta_;
  _impl_.meta_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::whiteboard::MessageMeta* WhiteboardMessage::unsafe_arena_release_meta() {
  // @@protoc_insertion_point(field_release:whiteboard.WhiteboardMessage.meta)
  
  ::whiteboard::MessageMeta* temp = _impl_.meta_;
  _impl_.meta_ = nullptr;
  return temp;
}
inline ::whiteboard::MessageMeta* WhiteboardMessage::_internal_mutable_meta() {
  
  if (_impl_.meta_ == nullptr) {
    auto* p = CreateMaybeMessage<::whiteboard::MessageMeta>(GetArenaForAllocation());
    _impl_.meta_ = p;
  }
  return _impl_.meta_;
}
inline ::whiteboard::MessageMeta* WhiteboardMessage::mutable_meta() {
  ::whiteboard::MessageMeta* _msg = _internal_mutable_meta();
  // @@protoc_insertion_point(field_mutable:whiteboard.WhiteboardMessage.meta)
  return _msg;
}
inline void WhiteboardMessage::set_allocated_meta(::whiteboard::MessageMeta* meta) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.meta_;
  }
  if (meta) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(meta);
    if (message_arena != submessage_arena) {
      meta = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, meta, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.meta_ = meta;
  // @@protoc_insertion_point(field_set_allocated:whiteboard.WhiteboardMessage.meta)
}

// .whiteboard.RoomOperateData room_data = 3;
inline bool WhiteboardMessage::_internal_has_room_data() const {
  return data_case() == kRoomData;
}
inline bool WhiteboardMessage::has_room_data() const {
  return _internal_has_room_data();
}
inline void WhiteboardMessage::set_has_room_data() {
  _impl_._oneof_case_[0] = kRoomData;
}
inline void WhiteboardMessage::clear_room_data() {
  if (_internal_has_room_data()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.data_.room_data_;
    }
    clear_has_data();
  }
}
inline ::whiteboard::RoomOperateData* WhiteboardMessage::release_room_data() {
  // @@protoc_insertion_point(field_release:whiteboard.WhiteboardMessage.room_data)
  if (_internal_has_room_data()) {
    clear_has_data();
    ::whiteboard::RoomOperateData* temp = _impl_.data_.room_data_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.data_.room_data_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::whiteboard::RoomOperateData& WhiteboardMessage::_internal_room_data() const {
  return _internal_has_room_data()
      ? *_impl_.data_.room_data_
      : reinterpret_cast< ::whiteboard::RoomOperateData&>(::whiteboard::_RoomOperateData_default_instance_);
}
inline const ::whiteboard::RoomOperateData& WhiteboardMessage::room_data() const {
  // @@protoc_insertion_point(field_get:whiteboard.WhiteboardMessage.room_data)
  return _internal_room_data();
}
inline ::whiteboard::RoomOperateData* WhiteboardMessage::unsafe_arena_release_room_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:whiteboard.WhiteboardMessage.room_data)
  if (_internal_has_room_data()) {
    clear_has_data();
    ::whiteboard::RoomOperateData* temp = _impl_.data_.room_data_;
    _impl_.data_.room_data_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void WhiteboardMessage::unsafe_arena_set_allocated_room_data(::whiteboard::RoomOperateData* room_data) {
  clear_data();
  if (room_data) {
    set_has_room_data();
    _impl_.data_.room_data_ = room_data;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:whiteboard.WhiteboardMessage.room_data)
}
inline ::whiteboard::RoomOperateData* WhiteboardMessage::_internal_mutable_room_data() {
  if (!_internal_has_room_data()) {
    clear_data();
    set_has_room_data();
    _impl_.data_.room_data_ = CreateMaybeMessage< ::whiteboard::RoomOperateData >(GetArenaForAllocation());
  }
  return _impl_.data_.room_data_;
}
inline ::whiteboard::RoomOperateData* WhiteboardMessage::mutable_room_data() {
  ::whiteboard::RoomOperateData* _msg = _internal_mutable_room_data();
  // @@protoc_insertion_point(field_mutable:whiteboard.WhiteboardMessage.room_data)
  return _msg;
}

// .whiteboard.DrawOperateData draw_data = 4;
inline bool WhiteboardMessage::_internal_has_draw_data() const {
  return data_case() == kDrawData;
}
inline bool WhiteboardMessage::has_draw_data() const {
  return _internal_has_draw_data();
}
inline void WhiteboardMessage::set_has_draw_data() {
  _impl_._oneof_case_[0] = kDrawData;
}
inline void WhiteboardMessage::clear_draw_data() {
  if (_internal_has_draw_data()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.data_.draw_data_;
    }
    clear_has_data();
  }
}
inline ::whiteboard::DrawOperateData* WhiteboardMessage::release_draw_data() {
  // @@protoc_insertion_point(field_release:whiteboard.WhiteboardMessage.draw_data)
  if (_internal_has_draw_data()) {
    clear_has_data();
    ::whiteboard::DrawOperateData* temp = _impl_.data_.draw_data_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.data_.draw_data_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::whiteboard::DrawOperateData& WhiteboardMessage::_internal_draw_data() const {
  return _internal_has_draw_data()
      ? *_impl_.data_.draw_data_
      : reinterpret_cast< ::whiteboard::DrawOperateData&>(::whiteboard::_DrawOperateData_default_instance_);
}
inline const ::whiteboard::DrawOperateData& WhiteboardMessage::draw_data() const {
  // @@protoc_insertion_point(field_get:whiteboard.WhiteboardMessage.draw_data)
  return _internal_draw_data();
}
inline ::whiteboard::DrawOperateData* WhiteboardMessage::unsafe_arena_release_draw_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:whiteboard.WhiteboardMessage.draw_data)
  if (_internal_has_draw_data()) {
    clear_has_data();
    ::whiteboard::DrawOperateData* temp = _impl_.data_.draw_data_;
    _impl_.data_.draw_data_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void WhiteboardMessage::unsafe_arena_set_allocated_draw_data(::whiteboard::DrawOperateData* draw_data) {
  clear_data();
  if (draw_data) {
    set_has_draw_data();
    _impl_.data_.draw_data_ = draw_data;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:whiteboard.WhiteboardMessage.draw_data)
}
inline ::whiteboard::DrawOperateData* WhiteboardMessage::_internal_mutable_draw_data() {
  if (!_internal_has_draw_data()) {
    clear_data();
    set_has_draw_data();
    _impl_.data_.draw_data_ = CreateMaybeMessage< ::whiteboard::DrawOperateData >(GetArenaForAllocation());
  }
  return _impl_.data_.draw_data_;
}
inline ::whiteboard::DrawOperateData* WhiteboardMessage::mutable_draw_data() {
  ::whiteboard::DrawOperateData* _msg = _internal_mutable_draw_data();
  // @@protoc_insertion_point(field_mutable:whiteboard.WhiteboardMessage.draw_data)
  return _msg;
}

inline bool WhiteboardMessage::has_data() const {
  return data_case() != DATA_NOT_SET;
}
inline void WhiteboardMessage::clear_has_data() {
  _impl_._oneof_case_[0] = DATA_NOT_SET;
}
inline WhiteboardMessage::DataCase WhiteboardMessage::data_case() const {
  return WhiteboardMessage::DataCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace whiteboard

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::whiteboard::OperateType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::whiteboard::OperateType>() {
  return ::whiteboard::OperateType_descriptor();
}
template <> struct is_proto_enum< ::whiteboard::OperateId> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::whiteboard::OperateId>() {
  return ::whiteboard::OperateId_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_white_5fboard_2eproto
