// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: white_board.proto

#include "white_board.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace whiteboard {
PROTOBUF_CONSTEXPR MessageHeader::MessageHeader(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.version_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.msg_id_)*/uint64_t{0u}
  , /*decltype(_impl_.timestamp_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MessageHeaderDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MessageHeaderDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MessageHeaderDefaultTypeInternal() {}
  union {
    MessageHeader _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MessageHeaderDefaultTypeInternal _MessageHeader_default_instance_;
PROTOBUF_CONSTEXPR MessageMeta::MessageMeta(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.user_id_)*/uint64_t{0u}
  , /*decltype(_impl_.room_id_)*/uint64_t{0u}
  , /*decltype(_impl_.operate_type_)*/0
  , /*decltype(_impl_.operate_id_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MessageMetaDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MessageMetaDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MessageMetaDefaultTypeInternal() {}
  union {
    MessageMeta _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MessageMetaDefaultTypeInternal _MessageMeta_default_instance_;
PROTOBUF_CONSTEXPR RoomOperateData::RoomOperateData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.room_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.password_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.user_nickname_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.reason_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.target_user_id_)*/uint64_t{0u}
  , /*decltype(_impl_.max_users_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RoomOperateDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RoomOperateDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RoomOperateDataDefaultTypeInternal() {}
  union {
    RoomOperateData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RoomOperateDataDefaultTypeInternal _RoomOperateData_default_instance_;
PROTOBUF_CONSTEXPR DrawOperateData::DrawOperateData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.color_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.line_width_)*/0
  , /*decltype(_impl_.start_x_)*/0
  , /*decltype(_impl_.start_y_)*/0
  , /*decltype(_impl_.end_x_)*/0
  , /*decltype(_impl_.end_y_)*/0
  , /*decltype(_impl_.center_x_)*/0
  , /*decltype(_impl_.center_y_)*/0
  , /*decltype(_impl_.radius_)*/0
  , /*decltype(_impl_.fill_)*/false
  , /*decltype(_impl_.left_x_)*/0
  , /*decltype(_impl_.top_y_)*/0
  , /*decltype(_impl_.width_)*/0
  , /*decltype(_impl_.shape_id_)*/uint64_t{0u}
  , /*decltype(_impl_.height_)*/0
  , /*decltype(_impl_.offset_x_)*/0
  , /*decltype(_impl_.offset_y_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DrawOperateDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DrawOperateDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DrawOperateDataDefaultTypeInternal() {}
  union {
    DrawOperateData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DrawOperateDataDefaultTypeInternal _DrawOperateData_default_instance_;
PROTOBUF_CONSTEXPR WhiteboardMessage::WhiteboardMessage(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.header_)*/nullptr
  , /*decltype(_impl_.meta_)*/nullptr
  , /*decltype(_impl_.data_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct WhiteboardMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WhiteboardMessageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~WhiteboardMessageDefaultTypeInternal() {}
  union {
    WhiteboardMessage _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WhiteboardMessageDefaultTypeInternal _WhiteboardMessage_default_instance_;
}  // namespace whiteboard
static ::_pb::Metadata file_level_metadata_white_5fboard_2eproto[5];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_white_5fboard_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_white_5fboard_2eproto = nullptr;

const uint32_t TableStruct_white_5fboard_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::whiteboard::MessageHeader, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::whiteboard::MessageHeader, _impl_.msg_id_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::MessageHeader, _impl_.timestamp_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::MessageHeader, _impl_.version_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::whiteboard::MessageMeta, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::whiteboard::MessageMeta, _impl_.user_id_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::MessageMeta, _impl_.room_id_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::MessageMeta, _impl_.operate_type_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::MessageMeta, _impl_.operate_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::whiteboard::RoomOperateData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::whiteboard::RoomOperateData, _impl_.room_name_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::RoomOperateData, _impl_.max_users_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::RoomOperateData, _impl_.password_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::RoomOperateData, _impl_.user_nickname_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::RoomOperateData, _impl_.reason_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::RoomOperateData, _impl_.target_user_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::whiteboard::DrawOperateData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::whiteboard::DrawOperateData, _impl_.color_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::DrawOperateData, _impl_.line_width_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::DrawOperateData, _impl_.start_x_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::DrawOperateData, _impl_.start_y_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::DrawOperateData, _impl_.end_x_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::DrawOperateData, _impl_.end_y_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::DrawOperateData, _impl_.center_x_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::DrawOperateData, _impl_.center_y_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::DrawOperateData, _impl_.radius_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::DrawOperateData, _impl_.fill_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::DrawOperateData, _impl_.left_x_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::DrawOperateData, _impl_.top_y_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::DrawOperateData, _impl_.width_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::DrawOperateData, _impl_.height_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::DrawOperateData, _impl_.shape_id_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::DrawOperateData, _impl_.offset_x_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::DrawOperateData, _impl_.offset_y_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::whiteboard::WhiteboardMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::whiteboard::WhiteboardMessage, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::whiteboard::WhiteboardMessage, _impl_.header_),
  PROTOBUF_FIELD_OFFSET(::whiteboard::WhiteboardMessage, _impl_.meta_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::whiteboard::WhiteboardMessage, _impl_.data_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::whiteboard::MessageHeader)},
  { 9, -1, -1, sizeof(::whiteboard::MessageMeta)},
  { 19, -1, -1, sizeof(::whiteboard::RoomOperateData)},
  { 31, -1, -1, sizeof(::whiteboard::DrawOperateData)},
  { 54, -1, -1, sizeof(::whiteboard::WhiteboardMessage)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::whiteboard::_MessageHeader_default_instance_._instance,
  &::whiteboard::_MessageMeta_default_instance_._instance,
  &::whiteboard::_RoomOperateData_default_instance_._instance,
  &::whiteboard::_DrawOperateData_default_instance_._instance,
  &::whiteboard::_WhiteboardMessage_default_instance_._instance,
};

const char descriptor_table_protodef_white_5fboard_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021white_board.proto\022\nwhiteboard\"C\n\rMessa"
  "geHeader\022\016\n\006msg_id\030\001 \001(\004\022\021\n\ttimestamp\030\002 "
  "\001(\004\022\017\n\007version\030\003 \001(\t\"\211\001\n\013MessageMeta\022\017\n\007"
  "user_id\030\001 \001(\004\022\017\n\007room_id\030\002 \001(\004\022-\n\014operat"
  "e_type\030\003 \001(\0162\027.whiteboard.OperateType\022)\n"
  "\noperate_id\030\004 \001(\0162\025.whiteboard.OperateId"
  "\"\210\001\n\017RoomOperateData\022\021\n\troom_name\030\001 \001(\t\022"
  "\021\n\tmax_users\030\002 \001(\r\022\020\n\010password\030\003 \001(\t\022\025\n\r"
  "user_nickname\030\004 \001(\t\022\016\n\006reason\030\005 \001(\t\022\026\n\016t"
  "arget_user_id\030\006 \001(\004\"\252\002\n\017DrawOperateData\022"
  "\r\n\005color\030\001 \001(\t\022\022\n\nline_width\030\002 \001(\002\022\017\n\007st"
  "art_x\030\003 \001(\002\022\017\n\007start_y\030\004 \001(\002\022\r\n\005end_x\030\005 "
  "\001(\002\022\r\n\005end_y\030\006 \001(\002\022\020\n\010center_x\030\007 \001(\002\022\020\n\010"
  "center_y\030\010 \001(\002\022\016\n\006radius\030\t \001(\002\022\014\n\004fill\030\n"
  " \001(\010\022\016\n\006left_x\030\013 \001(\002\022\r\n\005top_y\030\014 \001(\002\022\r\n\005w"
  "idth\030\r \001(\002\022\016\n\006height\030\016 \001(\002\022\020\n\010shape_id\030\017"
  " \001(\004\022\020\n\010offset_x\030\020 \001(\002\022\020\n\010offset_y\030\021 \001(\002"
  "\"\321\001\n\021WhiteboardMessage\022)\n\006header\030\001 \001(\0132\031"
  ".whiteboard.MessageHeader\022%\n\004meta\030\002 \001(\0132"
  "\027.whiteboard.MessageMeta\0220\n\troom_data\030\003 "
  "\001(\0132\033.whiteboard.RoomOperateDataH\000\0220\n\tdr"
  "aw_data\030\004 \001(\0132\033.whiteboard.DrawOperateDa"
  "taH\000B\006\n\004data*U\n\013OperateType\022\030\n\024OPERATE_T"
  "YPE_UNKNOWN\020\000\022\025\n\021OPERATE_TYPE_ROOM\020\001\022\025\n\021"
  "OPERATE_TYPE_DRAW\020\002*\264\001\n\tOperateId\022\026\n\022OPE"
  "RATE_ID_UNKNOWN\020\000\022\017\n\013ROOM_CREATE\020e\022\r\n\tRO"
  "OM_JOIN\020f\022\r\n\tROOM_EXIT\020g\022\r\n\tROOM_KICK\020h\022"
  "\016\n\tDRAW_LINE\020\311\001\022\020\n\013DRAW_CIRCLE\020\312\001\022\016\n\tDRA"
  "W_RECT\020\313\001\022\017\n\nDRAW_ERASE\020\314\001\022\016\n\tDRAW_MOVE\020"
  "\315\001b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_white_5fboard_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_white_5fboard_2eproto = {
    false, false, 1170, descriptor_table_protodef_white_5fboard_2eproto,
    "white_board.proto",
    &descriptor_table_white_5fboard_2eproto_once, nullptr, 0, 5,
    schemas, file_default_instances, TableStruct_white_5fboard_2eproto::offsets,
    file_level_metadata_white_5fboard_2eproto, file_level_enum_descriptors_white_5fboard_2eproto,
    file_level_service_descriptors_white_5fboard_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_white_5fboard_2eproto_getter() {
  return &descriptor_table_white_5fboard_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_white_5fboard_2eproto(&descriptor_table_white_5fboard_2eproto);
namespace whiteboard {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* OperateType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_white_5fboard_2eproto);
  return file_level_enum_descriptors_white_5fboard_2eproto[0];
}
bool OperateType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* OperateId_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_white_5fboard_2eproto);
  return file_level_enum_descriptors_white_5fboard_2eproto[1];
}
bool OperateId_IsValid(int value) {
  switch (value) {
    case 0:
    case 101:
    case 102:
    case 103:
    case 104:
    case 201:
    case 202:
    case 203:
    case 204:
    case 205:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class MessageHeader::_Internal {
 public:
};

MessageHeader::MessageHeader(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:whiteboard.MessageHeader)
}
MessageHeader::MessageHeader(const MessageHeader& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MessageHeader* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.version_){}
    , decltype(_impl_.msg_id_){}
    , decltype(_impl_.timestamp_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_version().empty()) {
    _this->_impl_.version_.Set(from._internal_version(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.msg_id_, &from._impl_.msg_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.timestamp_) -
    reinterpret_cast<char*>(&_impl_.msg_id_)) + sizeof(_impl_.timestamp_));
  // @@protoc_insertion_point(copy_constructor:whiteboard.MessageHeader)
}

inline void MessageHeader::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.version_){}
    , decltype(_impl_.msg_id_){uint64_t{0u}}
    , decltype(_impl_.timestamp_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

MessageHeader::~MessageHeader() {
  // @@protoc_insertion_point(destructor:whiteboard.MessageHeader)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MessageHeader::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.version_.Destroy();
}

void MessageHeader::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MessageHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:whiteboard.MessageHeader)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.version_.ClearToEmpty();
  ::memset(&_impl_.msg_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.timestamp_) -
      reinterpret_cast<char*>(&_impl_.msg_id_)) + sizeof(_impl_.timestamp_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MessageHeader::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 msg_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.msg_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 timestamp = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string version = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_version();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "whiteboard.MessageHeader.version"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MessageHeader::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:whiteboard.MessageHeader)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 msg_id = 1;
  if (this->_internal_msg_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_msg_id(), target);
  }

  // uint64 timestamp = 2;
  if (this->_internal_timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_timestamp(), target);
  }

  // string version = 3;
  if (!this->_internal_version().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_version().data(), static_cast<int>(this->_internal_version().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "whiteboard.MessageHeader.version");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_version(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:whiteboard.MessageHeader)
  return target;
}

size_t MessageHeader::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:whiteboard.MessageHeader)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string version = 3;
  if (!this->_internal_version().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_version());
  }

  // uint64 msg_id = 1;
  if (this->_internal_msg_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_msg_id());
  }

  // uint64 timestamp = 2;
  if (this->_internal_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_timestamp());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MessageHeader::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MessageHeader::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MessageHeader::GetClassData() const { return &_class_data_; }


void MessageHeader::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MessageHeader*>(&to_msg);
  auto& from = static_cast<const MessageHeader&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:whiteboard.MessageHeader)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_version().empty()) {
    _this->_internal_set_version(from._internal_version());
  }
  if (from._internal_msg_id() != 0) {
    _this->_internal_set_msg_id(from._internal_msg_id());
  }
  if (from._internal_timestamp() != 0) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MessageHeader::CopyFrom(const MessageHeader& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:whiteboard.MessageHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageHeader::IsInitialized() const {
  return true;
}

void MessageHeader::InternalSwap(MessageHeader* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.version_, lhs_arena,
      &other->_impl_.version_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MessageHeader, _impl_.timestamp_)
      + sizeof(MessageHeader::_impl_.timestamp_)
      - PROTOBUF_FIELD_OFFSET(MessageHeader, _impl_.msg_id_)>(
          reinterpret_cast<char*>(&_impl_.msg_id_),
          reinterpret_cast<char*>(&other->_impl_.msg_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MessageHeader::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_white_5fboard_2eproto_getter, &descriptor_table_white_5fboard_2eproto_once,
      file_level_metadata_white_5fboard_2eproto[0]);
}

// ===================================================================

class MessageMeta::_Internal {
 public:
};

MessageMeta::MessageMeta(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:whiteboard.MessageMeta)
}
MessageMeta::MessageMeta(const MessageMeta& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MessageMeta* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.user_id_){}
    , decltype(_impl_.room_id_){}
    , decltype(_impl_.operate_type_){}
    , decltype(_impl_.operate_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.user_id_, &from._impl_.user_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.operate_id_) -
    reinterpret_cast<char*>(&_impl_.user_id_)) + sizeof(_impl_.operate_id_));
  // @@protoc_insertion_point(copy_constructor:whiteboard.MessageMeta)
}

inline void MessageMeta::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.user_id_){uint64_t{0u}}
    , decltype(_impl_.room_id_){uint64_t{0u}}
    , decltype(_impl_.operate_type_){0}
    , decltype(_impl_.operate_id_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MessageMeta::~MessageMeta() {
  // @@protoc_insertion_point(destructor:whiteboard.MessageMeta)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MessageMeta::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void MessageMeta::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MessageMeta::Clear() {
// @@protoc_insertion_point(message_clear_start:whiteboard.MessageMeta)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.user_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.operate_id_) -
      reinterpret_cast<char*>(&_impl_.user_id_)) + sizeof(_impl_.operate_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MessageMeta::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 user_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.user_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 room_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.room_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .whiteboard.OperateType operate_type = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_operate_type(static_cast<::whiteboard::OperateType>(val));
        } else
          goto handle_unusual;
        continue;
      // .whiteboard.OperateId operate_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_operate_id(static_cast<::whiteboard::OperateId>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MessageMeta::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:whiteboard.MessageMeta)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 user_id = 1;
  if (this->_internal_user_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_user_id(), target);
  }

  // uint64 room_id = 2;
  if (this->_internal_room_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_room_id(), target);
  }

  // .whiteboard.OperateType operate_type = 3;
  if (this->_internal_operate_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      3, this->_internal_operate_type(), target);
  }

  // .whiteboard.OperateId operate_id = 4;
  if (this->_internal_operate_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      4, this->_internal_operate_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:whiteboard.MessageMeta)
  return target;
}

size_t MessageMeta::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:whiteboard.MessageMeta)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 user_id = 1;
  if (this->_internal_user_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_user_id());
  }

  // uint64 room_id = 2;
  if (this->_internal_room_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_room_id());
  }

  // .whiteboard.OperateType operate_type = 3;
  if (this->_internal_operate_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_operate_type());
  }

  // .whiteboard.OperateId operate_id = 4;
  if (this->_internal_operate_id() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_operate_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MessageMeta::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MessageMeta::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MessageMeta::GetClassData() const { return &_class_data_; }


void MessageMeta::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MessageMeta*>(&to_msg);
  auto& from = static_cast<const MessageMeta&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:whiteboard.MessageMeta)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_user_id() != 0) {
    _this->_internal_set_user_id(from._internal_user_id());
  }
  if (from._internal_room_id() != 0) {
    _this->_internal_set_room_id(from._internal_room_id());
  }
  if (from._internal_operate_type() != 0) {
    _this->_internal_set_operate_type(from._internal_operate_type());
  }
  if (from._internal_operate_id() != 0) {
    _this->_internal_set_operate_id(from._internal_operate_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MessageMeta::CopyFrom(const MessageMeta& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:whiteboard.MessageMeta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageMeta::IsInitialized() const {
  return true;
}

void MessageMeta::InternalSwap(MessageMeta* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MessageMeta, _impl_.operate_id_)
      + sizeof(MessageMeta::_impl_.operate_id_)
      - PROTOBUF_FIELD_OFFSET(MessageMeta, _impl_.user_id_)>(
          reinterpret_cast<char*>(&_impl_.user_id_),
          reinterpret_cast<char*>(&other->_impl_.user_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MessageMeta::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_white_5fboard_2eproto_getter, &descriptor_table_white_5fboard_2eproto_once,
      file_level_metadata_white_5fboard_2eproto[1]);
}

// ===================================================================

class RoomOperateData::_Internal {
 public:
};

RoomOperateData::RoomOperateData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:whiteboard.RoomOperateData)
}
RoomOperateData::RoomOperateData(const RoomOperateData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RoomOperateData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.room_name_){}
    , decltype(_impl_.password_){}
    , decltype(_impl_.user_nickname_){}
    , decltype(_impl_.reason_){}
    , decltype(_impl_.target_user_id_){}
    , decltype(_impl_.max_users_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.room_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.room_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_room_name().empty()) {
    _this->_impl_.room_name_.Set(from._internal_room_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.password_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.password_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_password().empty()) {
    _this->_impl_.password_.Set(from._internal_password(), 
      _this->GetArenaForAllocation());
  }
  _impl_.user_nickname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.user_nickname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_user_nickname().empty()) {
    _this->_impl_.user_nickname_.Set(from._internal_user_nickname(), 
      _this->GetArenaForAllocation());
  }
  _impl_.reason_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.reason_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_reason().empty()) {
    _this->_impl_.reason_.Set(from._internal_reason(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.target_user_id_, &from._impl_.target_user_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.max_users_) -
    reinterpret_cast<char*>(&_impl_.target_user_id_)) + sizeof(_impl_.max_users_));
  // @@protoc_insertion_point(copy_constructor:whiteboard.RoomOperateData)
}

inline void RoomOperateData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.room_name_){}
    , decltype(_impl_.password_){}
    , decltype(_impl_.user_nickname_){}
    , decltype(_impl_.reason_){}
    , decltype(_impl_.target_user_id_){uint64_t{0u}}
    , decltype(_impl_.max_users_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.room_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.room_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.password_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.password_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.user_nickname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.user_nickname_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.reason_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.reason_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

RoomOperateData::~RoomOperateData() {
  // @@protoc_insertion_point(destructor:whiteboard.RoomOperateData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RoomOperateData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.room_name_.Destroy();
  _impl_.password_.Destroy();
  _impl_.user_nickname_.Destroy();
  _impl_.reason_.Destroy();
}

void RoomOperateData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RoomOperateData::Clear() {
// @@protoc_insertion_point(message_clear_start:whiteboard.RoomOperateData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.room_name_.ClearToEmpty();
  _impl_.password_.ClearToEmpty();
  _impl_.user_nickname_.ClearToEmpty();
  _impl_.reason_.ClearToEmpty();
  ::memset(&_impl_.target_user_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.max_users_) -
      reinterpret_cast<char*>(&_impl_.target_user_id_)) + sizeof(_impl_.max_users_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RoomOperateData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string room_name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_room_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "whiteboard.RoomOperateData.room_name"));
        } else
          goto handle_unusual;
        continue;
      // uint32 max_users = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.max_users_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string password = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_password();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "whiteboard.RoomOperateData.password"));
        } else
          goto handle_unusual;
        continue;
      // string user_nickname = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_user_nickname();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "whiteboard.RoomOperateData.user_nickname"));
        } else
          goto handle_unusual;
        continue;
      // string reason = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_reason();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "whiteboard.RoomOperateData.reason"));
        } else
          goto handle_unusual;
        continue;
      // uint64 target_user_id = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.target_user_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RoomOperateData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:whiteboard.RoomOperateData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string room_name = 1;
  if (!this->_internal_room_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_room_name().data(), static_cast<int>(this->_internal_room_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "whiteboard.RoomOperateData.room_name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_room_name(), target);
  }

  // uint32 max_users = 2;
  if (this->_internal_max_users() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_max_users(), target);
  }

  // string password = 3;
  if (!this->_internal_password().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_password().data(), static_cast<int>(this->_internal_password().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "whiteboard.RoomOperateData.password");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_password(), target);
  }

  // string user_nickname = 4;
  if (!this->_internal_user_nickname().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_user_nickname().data(), static_cast<int>(this->_internal_user_nickname().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "whiteboard.RoomOperateData.user_nickname");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_user_nickname(), target);
  }

  // string reason = 5;
  if (!this->_internal_reason().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_reason().data(), static_cast<int>(this->_internal_reason().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "whiteboard.RoomOperateData.reason");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_reason(), target);
  }

  // uint64 target_user_id = 6;
  if (this->_internal_target_user_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(6, this->_internal_target_user_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:whiteboard.RoomOperateData)
  return target;
}

size_t RoomOperateData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:whiteboard.RoomOperateData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string room_name = 1;
  if (!this->_internal_room_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_room_name());
  }

  // string password = 3;
  if (!this->_internal_password().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_password());
  }

  // string user_nickname = 4;
  if (!this->_internal_user_nickname().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_user_nickname());
  }

  // string reason = 5;
  if (!this->_internal_reason().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_reason());
  }

  // uint64 target_user_id = 6;
  if (this->_internal_target_user_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_target_user_id());
  }

  // uint32 max_users = 2;
  if (this->_internal_max_users() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_max_users());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RoomOperateData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RoomOperateData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RoomOperateData::GetClassData() const { return &_class_data_; }


void RoomOperateData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RoomOperateData*>(&to_msg);
  auto& from = static_cast<const RoomOperateData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:whiteboard.RoomOperateData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_room_name().empty()) {
    _this->_internal_set_room_name(from._internal_room_name());
  }
  if (!from._internal_password().empty()) {
    _this->_internal_set_password(from._internal_password());
  }
  if (!from._internal_user_nickname().empty()) {
    _this->_internal_set_user_nickname(from._internal_user_nickname());
  }
  if (!from._internal_reason().empty()) {
    _this->_internal_set_reason(from._internal_reason());
  }
  if (from._internal_target_user_id() != 0) {
    _this->_internal_set_target_user_id(from._internal_target_user_id());
  }
  if (from._internal_max_users() != 0) {
    _this->_internal_set_max_users(from._internal_max_users());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RoomOperateData::CopyFrom(const RoomOperateData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:whiteboard.RoomOperateData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RoomOperateData::IsInitialized() const {
  return true;
}

void RoomOperateData::InternalSwap(RoomOperateData* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.room_name_, lhs_arena,
      &other->_impl_.room_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.password_, lhs_arena,
      &other->_impl_.password_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.user_nickname_, lhs_arena,
      &other->_impl_.user_nickname_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.reason_, lhs_arena,
      &other->_impl_.reason_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RoomOperateData, _impl_.max_users_)
      + sizeof(RoomOperateData::_impl_.max_users_)
      - PROTOBUF_FIELD_OFFSET(RoomOperateData, _impl_.target_user_id_)>(
          reinterpret_cast<char*>(&_impl_.target_user_id_),
          reinterpret_cast<char*>(&other->_impl_.target_user_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RoomOperateData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_white_5fboard_2eproto_getter, &descriptor_table_white_5fboard_2eproto_once,
      file_level_metadata_white_5fboard_2eproto[2]);
}

// ===================================================================

class DrawOperateData::_Internal {
 public:
};

DrawOperateData::DrawOperateData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:whiteboard.DrawOperateData)
}
DrawOperateData::DrawOperateData(const DrawOperateData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DrawOperateData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.color_){}
    , decltype(_impl_.line_width_){}
    , decltype(_impl_.start_x_){}
    , decltype(_impl_.start_y_){}
    , decltype(_impl_.end_x_){}
    , decltype(_impl_.end_y_){}
    , decltype(_impl_.center_x_){}
    , decltype(_impl_.center_y_){}
    , decltype(_impl_.radius_){}
    , decltype(_impl_.fill_){}
    , decltype(_impl_.left_x_){}
    , decltype(_impl_.top_y_){}
    , decltype(_impl_.width_){}
    , decltype(_impl_.shape_id_){}
    , decltype(_impl_.height_){}
    , decltype(_impl_.offset_x_){}
    , decltype(_impl_.offset_y_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.color_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.color_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_color().empty()) {
    _this->_impl_.color_.Set(from._internal_color(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.line_width_, &from._impl_.line_width_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.offset_y_) -
    reinterpret_cast<char*>(&_impl_.line_width_)) + sizeof(_impl_.offset_y_));
  // @@protoc_insertion_point(copy_constructor:whiteboard.DrawOperateData)
}

inline void DrawOperateData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.color_){}
    , decltype(_impl_.line_width_){0}
    , decltype(_impl_.start_x_){0}
    , decltype(_impl_.start_y_){0}
    , decltype(_impl_.end_x_){0}
    , decltype(_impl_.end_y_){0}
    , decltype(_impl_.center_x_){0}
    , decltype(_impl_.center_y_){0}
    , decltype(_impl_.radius_){0}
    , decltype(_impl_.fill_){false}
    , decltype(_impl_.left_x_){0}
    , decltype(_impl_.top_y_){0}
    , decltype(_impl_.width_){0}
    , decltype(_impl_.shape_id_){uint64_t{0u}}
    , decltype(_impl_.height_){0}
    , decltype(_impl_.offset_x_){0}
    , decltype(_impl_.offset_y_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.color_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.color_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

DrawOperateData::~DrawOperateData() {
  // @@protoc_insertion_point(destructor:whiteboard.DrawOperateData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DrawOperateData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.color_.Destroy();
}

void DrawOperateData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DrawOperateData::Clear() {
// @@protoc_insertion_point(message_clear_start:whiteboard.DrawOperateData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.color_.ClearToEmpty();
  ::memset(&_impl_.line_width_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.offset_y_) -
      reinterpret_cast<char*>(&_impl_.line_width_)) + sizeof(_impl_.offset_y_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DrawOperateData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string color = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_color();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "whiteboard.DrawOperateData.color"));
        } else
          goto handle_unusual;
        continue;
      // float line_width = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.line_width_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float start_x = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 29)) {
          _impl_.start_x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float start_y = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 37)) {
          _impl_.start_y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float end_x = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 45)) {
          _impl_.end_x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float end_y = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 53)) {
          _impl_.end_y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float center_x = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 61)) {
          _impl_.center_x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float center_y = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 69)) {
          _impl_.center_y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float radius = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 77)) {
          _impl_.radius_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // bool fill = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          _impl_.fill_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float left_x = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 93)) {
          _impl_.left_x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float top_y = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 101)) {
          _impl_.top_y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float width = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 109)) {
          _impl_.width_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float height = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 117)) {
          _impl_.height_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // uint64 shape_id = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 120)) {
          _impl_.shape_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float offset_x = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 133)) {
          _impl_.offset_x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float offset_y = 17;
      case 17:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 141)) {
          _impl_.offset_y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DrawOperateData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:whiteboard.DrawOperateData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string color = 1;
  if (!this->_internal_color().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_color().data(), static_cast<int>(this->_internal_color().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "whiteboard.DrawOperateData.color");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_color(), target);
  }

  // float line_width = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_line_width = this->_internal_line_width();
  uint32_t raw_line_width;
  memcpy(&raw_line_width, &tmp_line_width, sizeof(tmp_line_width));
  if (raw_line_width != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_line_width(), target);
  }

  // float start_x = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_start_x = this->_internal_start_x();
  uint32_t raw_start_x;
  memcpy(&raw_start_x, &tmp_start_x, sizeof(tmp_start_x));
  if (raw_start_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(3, this->_internal_start_x(), target);
  }

  // float start_y = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_start_y = this->_internal_start_y();
  uint32_t raw_start_y;
  memcpy(&raw_start_y, &tmp_start_y, sizeof(tmp_start_y));
  if (raw_start_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(4, this->_internal_start_y(), target);
  }

  // float end_x = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_end_x = this->_internal_end_x();
  uint32_t raw_end_x;
  memcpy(&raw_end_x, &tmp_end_x, sizeof(tmp_end_x));
  if (raw_end_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(5, this->_internal_end_x(), target);
  }

  // float end_y = 6;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_end_y = this->_internal_end_y();
  uint32_t raw_end_y;
  memcpy(&raw_end_y, &tmp_end_y, sizeof(tmp_end_y));
  if (raw_end_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(6, this->_internal_end_y(), target);
  }

  // float center_x = 7;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_center_x = this->_internal_center_x();
  uint32_t raw_center_x;
  memcpy(&raw_center_x, &tmp_center_x, sizeof(tmp_center_x));
  if (raw_center_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(7, this->_internal_center_x(), target);
  }

  // float center_y = 8;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_center_y = this->_internal_center_y();
  uint32_t raw_center_y;
  memcpy(&raw_center_y, &tmp_center_y, sizeof(tmp_center_y));
  if (raw_center_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(8, this->_internal_center_y(), target);
  }

  // float radius = 9;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_radius = this->_internal_radius();
  uint32_t raw_radius;
  memcpy(&raw_radius, &tmp_radius, sizeof(tmp_radius));
  if (raw_radius != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(9, this->_internal_radius(), target);
  }

  // bool fill = 10;
  if (this->_internal_fill() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(10, this->_internal_fill(), target);
  }

  // float left_x = 11;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_left_x = this->_internal_left_x();
  uint32_t raw_left_x;
  memcpy(&raw_left_x, &tmp_left_x, sizeof(tmp_left_x));
  if (raw_left_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(11, this->_internal_left_x(), target);
  }

  // float top_y = 12;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_top_y = this->_internal_top_y();
  uint32_t raw_top_y;
  memcpy(&raw_top_y, &tmp_top_y, sizeof(tmp_top_y));
  if (raw_top_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(12, this->_internal_top_y(), target);
  }

  // float width = 13;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_width = this->_internal_width();
  uint32_t raw_width;
  memcpy(&raw_width, &tmp_width, sizeof(tmp_width));
  if (raw_width != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(13, this->_internal_width(), target);
  }

  // float height = 14;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_height = this->_internal_height();
  uint32_t raw_height;
  memcpy(&raw_height, &tmp_height, sizeof(tmp_height));
  if (raw_height != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(14, this->_internal_height(), target);
  }

  // uint64 shape_id = 15;
  if (this->_internal_shape_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(15, this->_internal_shape_id(), target);
  }

  // float offset_x = 16;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_offset_x = this->_internal_offset_x();
  uint32_t raw_offset_x;
  memcpy(&raw_offset_x, &tmp_offset_x, sizeof(tmp_offset_x));
  if (raw_offset_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(16, this->_internal_offset_x(), target);
  }

  // float offset_y = 17;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_offset_y = this->_internal_offset_y();
  uint32_t raw_offset_y;
  memcpy(&raw_offset_y, &tmp_offset_y, sizeof(tmp_offset_y));
  if (raw_offset_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(17, this->_internal_offset_y(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:whiteboard.DrawOperateData)
  return target;
}

size_t DrawOperateData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:whiteboard.DrawOperateData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string color = 1;
  if (!this->_internal_color().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_color());
  }

  // float line_width = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_line_width = this->_internal_line_width();
  uint32_t raw_line_width;
  memcpy(&raw_line_width, &tmp_line_width, sizeof(tmp_line_width));
  if (raw_line_width != 0) {
    total_size += 1 + 4;
  }

  // float start_x = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_start_x = this->_internal_start_x();
  uint32_t raw_start_x;
  memcpy(&raw_start_x, &tmp_start_x, sizeof(tmp_start_x));
  if (raw_start_x != 0) {
    total_size += 1 + 4;
  }

  // float start_y = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_start_y = this->_internal_start_y();
  uint32_t raw_start_y;
  memcpy(&raw_start_y, &tmp_start_y, sizeof(tmp_start_y));
  if (raw_start_y != 0) {
    total_size += 1 + 4;
  }

  // float end_x = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_end_x = this->_internal_end_x();
  uint32_t raw_end_x;
  memcpy(&raw_end_x, &tmp_end_x, sizeof(tmp_end_x));
  if (raw_end_x != 0) {
    total_size += 1 + 4;
  }

  // float end_y = 6;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_end_y = this->_internal_end_y();
  uint32_t raw_end_y;
  memcpy(&raw_end_y, &tmp_end_y, sizeof(tmp_end_y));
  if (raw_end_y != 0) {
    total_size += 1 + 4;
  }

  // float center_x = 7;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_center_x = this->_internal_center_x();
  uint32_t raw_center_x;
  memcpy(&raw_center_x, &tmp_center_x, sizeof(tmp_center_x));
  if (raw_center_x != 0) {
    total_size += 1 + 4;
  }

  // float center_y = 8;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_center_y = this->_internal_center_y();
  uint32_t raw_center_y;
  memcpy(&raw_center_y, &tmp_center_y, sizeof(tmp_center_y));
  if (raw_center_y != 0) {
    total_size += 1 + 4;
  }

  // float radius = 9;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_radius = this->_internal_radius();
  uint32_t raw_radius;
  memcpy(&raw_radius, &tmp_radius, sizeof(tmp_radius));
  if (raw_radius != 0) {
    total_size += 1 + 4;
  }

  // bool fill = 10;
  if (this->_internal_fill() != 0) {
    total_size += 1 + 1;
  }

  // float left_x = 11;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_left_x = this->_internal_left_x();
  uint32_t raw_left_x;
  memcpy(&raw_left_x, &tmp_left_x, sizeof(tmp_left_x));
  if (raw_left_x != 0) {
    total_size += 1 + 4;
  }

  // float top_y = 12;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_top_y = this->_internal_top_y();
  uint32_t raw_top_y;
  memcpy(&raw_top_y, &tmp_top_y, sizeof(tmp_top_y));
  if (raw_top_y != 0) {
    total_size += 1 + 4;
  }

  // float width = 13;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_width = this->_internal_width();
  uint32_t raw_width;
  memcpy(&raw_width, &tmp_width, sizeof(tmp_width));
  if (raw_width != 0) {
    total_size += 1 + 4;
  }

  // uint64 shape_id = 15;
  if (this->_internal_shape_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_shape_id());
  }

  // float height = 14;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_height = this->_internal_height();
  uint32_t raw_height;
  memcpy(&raw_height, &tmp_height, sizeof(tmp_height));
  if (raw_height != 0) {
    total_size += 1 + 4;
  }

  // float offset_x = 16;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_offset_x = this->_internal_offset_x();
  uint32_t raw_offset_x;
  memcpy(&raw_offset_x, &tmp_offset_x, sizeof(tmp_offset_x));
  if (raw_offset_x != 0) {
    total_size += 2 + 4;
  }

  // float offset_y = 17;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_offset_y = this->_internal_offset_y();
  uint32_t raw_offset_y;
  memcpy(&raw_offset_y, &tmp_offset_y, sizeof(tmp_offset_y));
  if (raw_offset_y != 0) {
    total_size += 2 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DrawOperateData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DrawOperateData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DrawOperateData::GetClassData() const { return &_class_data_; }


void DrawOperateData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DrawOperateData*>(&to_msg);
  auto& from = static_cast<const DrawOperateData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:whiteboard.DrawOperateData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_color().empty()) {
    _this->_internal_set_color(from._internal_color());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_line_width = from._internal_line_width();
  uint32_t raw_line_width;
  memcpy(&raw_line_width, &tmp_line_width, sizeof(tmp_line_width));
  if (raw_line_width != 0) {
    _this->_internal_set_line_width(from._internal_line_width());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_start_x = from._internal_start_x();
  uint32_t raw_start_x;
  memcpy(&raw_start_x, &tmp_start_x, sizeof(tmp_start_x));
  if (raw_start_x != 0) {
    _this->_internal_set_start_x(from._internal_start_x());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_start_y = from._internal_start_y();
  uint32_t raw_start_y;
  memcpy(&raw_start_y, &tmp_start_y, sizeof(tmp_start_y));
  if (raw_start_y != 0) {
    _this->_internal_set_start_y(from._internal_start_y());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_end_x = from._internal_end_x();
  uint32_t raw_end_x;
  memcpy(&raw_end_x, &tmp_end_x, sizeof(tmp_end_x));
  if (raw_end_x != 0) {
    _this->_internal_set_end_x(from._internal_end_x());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_end_y = from._internal_end_y();
  uint32_t raw_end_y;
  memcpy(&raw_end_y, &tmp_end_y, sizeof(tmp_end_y));
  if (raw_end_y != 0) {
    _this->_internal_set_end_y(from._internal_end_y());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_center_x = from._internal_center_x();
  uint32_t raw_center_x;
  memcpy(&raw_center_x, &tmp_center_x, sizeof(tmp_center_x));
  if (raw_center_x != 0) {
    _this->_internal_set_center_x(from._internal_center_x());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_center_y = from._internal_center_y();
  uint32_t raw_center_y;
  memcpy(&raw_center_y, &tmp_center_y, sizeof(tmp_center_y));
  if (raw_center_y != 0) {
    _this->_internal_set_center_y(from._internal_center_y());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_radius = from._internal_radius();
  uint32_t raw_radius;
  memcpy(&raw_radius, &tmp_radius, sizeof(tmp_radius));
  if (raw_radius != 0) {
    _this->_internal_set_radius(from._internal_radius());
  }
  if (from._internal_fill() != 0) {
    _this->_internal_set_fill(from._internal_fill());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_left_x = from._internal_left_x();
  uint32_t raw_left_x;
  memcpy(&raw_left_x, &tmp_left_x, sizeof(tmp_left_x));
  if (raw_left_x != 0) {
    _this->_internal_set_left_x(from._internal_left_x());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_top_y = from._internal_top_y();
  uint32_t raw_top_y;
  memcpy(&raw_top_y, &tmp_top_y, sizeof(tmp_top_y));
  if (raw_top_y != 0) {
    _this->_internal_set_top_y(from._internal_top_y());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_width = from._internal_width();
  uint32_t raw_width;
  memcpy(&raw_width, &tmp_width, sizeof(tmp_width));
  if (raw_width != 0) {
    _this->_internal_set_width(from._internal_width());
  }
  if (from._internal_shape_id() != 0) {
    _this->_internal_set_shape_id(from._internal_shape_id());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_height = from._internal_height();
  uint32_t raw_height;
  memcpy(&raw_height, &tmp_height, sizeof(tmp_height));
  if (raw_height != 0) {
    _this->_internal_set_height(from._internal_height());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_offset_x = from._internal_offset_x();
  uint32_t raw_offset_x;
  memcpy(&raw_offset_x, &tmp_offset_x, sizeof(tmp_offset_x));
  if (raw_offset_x != 0) {
    _this->_internal_set_offset_x(from._internal_offset_x());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_offset_y = from._internal_offset_y();
  uint32_t raw_offset_y;
  memcpy(&raw_offset_y, &tmp_offset_y, sizeof(tmp_offset_y));
  if (raw_offset_y != 0) {
    _this->_internal_set_offset_y(from._internal_offset_y());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DrawOperateData::CopyFrom(const DrawOperateData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:whiteboard.DrawOperateData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DrawOperateData::IsInitialized() const {
  return true;
}

void DrawOperateData::InternalSwap(DrawOperateData* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.color_, lhs_arena,
      &other->_impl_.color_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DrawOperateData, _impl_.offset_y_)
      + sizeof(DrawOperateData::_impl_.offset_y_)
      - PROTOBUF_FIELD_OFFSET(DrawOperateData, _impl_.line_width_)>(
          reinterpret_cast<char*>(&_impl_.line_width_),
          reinterpret_cast<char*>(&other->_impl_.line_width_));
}

::PROTOBUF_NAMESPACE_ID::Metadata DrawOperateData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_white_5fboard_2eproto_getter, &descriptor_table_white_5fboard_2eproto_once,
      file_level_metadata_white_5fboard_2eproto[3]);
}

// ===================================================================

class WhiteboardMessage::_Internal {
 public:
  static const ::whiteboard::MessageHeader& header(const WhiteboardMessage* msg);
  static const ::whiteboard::MessageMeta& meta(const WhiteboardMessage* msg);
  static const ::whiteboard::RoomOperateData& room_data(const WhiteboardMessage* msg);
  static const ::whiteboard::DrawOperateData& draw_data(const WhiteboardMessage* msg);
};

const ::whiteboard::MessageHeader&
WhiteboardMessage::_Internal::header(const WhiteboardMessage* msg) {
  return *msg->_impl_.header_;
}
const ::whiteboard::MessageMeta&
WhiteboardMessage::_Internal::meta(const WhiteboardMessage* msg) {
  return *msg->_impl_.meta_;
}
const ::whiteboard::RoomOperateData&
WhiteboardMessage::_Internal::room_data(const WhiteboardMessage* msg) {
  return *msg->_impl_.data_.room_data_;
}
const ::whiteboard::DrawOperateData&
WhiteboardMessage::_Internal::draw_data(const WhiteboardMessage* msg) {
  return *msg->_impl_.data_.draw_data_;
}
void WhiteboardMessage::set_allocated_room_data(::whiteboard::RoomOperateData* room_data) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_data();
  if (room_data) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(room_data);
    if (message_arena != submessage_arena) {
      room_data = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, room_data, submessage_arena);
    }
    set_has_room_data();
    _impl_.data_.room_data_ = room_data;
  }
  // @@protoc_insertion_point(field_set_allocated:whiteboard.WhiteboardMessage.room_data)
}
void WhiteboardMessage::set_allocated_draw_data(::whiteboard::DrawOperateData* draw_data) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_data();
  if (draw_data) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(draw_data);
    if (message_arena != submessage_arena) {
      draw_data = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, draw_data, submessage_arena);
    }
    set_has_draw_data();
    _impl_.data_.draw_data_ = draw_data;
  }
  // @@protoc_insertion_point(field_set_allocated:whiteboard.WhiteboardMessage.draw_data)
}
WhiteboardMessage::WhiteboardMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:whiteboard.WhiteboardMessage)
}
WhiteboardMessage::WhiteboardMessage(const WhiteboardMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  WhiteboardMessage* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.header_){nullptr}
    , decltype(_impl_.meta_){nullptr}
    , decltype(_impl_.data_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_header()) {
    _this->_impl_.header_ = new ::whiteboard::MessageHeader(*from._impl_.header_);
  }
  if (from._internal_has_meta()) {
    _this->_impl_.meta_ = new ::whiteboard::MessageMeta(*from._impl_.meta_);
  }
  clear_has_data();
  switch (from.data_case()) {
    case kRoomData: {
      _this->_internal_mutable_room_data()->::whiteboard::RoomOperateData::MergeFrom(
          from._internal_room_data());
      break;
    }
    case kDrawData: {
      _this->_internal_mutable_draw_data()->::whiteboard::DrawOperateData::MergeFrom(
          from._internal_draw_data());
      break;
    }
    case DATA_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:whiteboard.WhiteboardMessage)
}

inline void WhiteboardMessage::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.header_){nullptr}
    , decltype(_impl_.meta_){nullptr}
    , decltype(_impl_.data_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_data();
}

WhiteboardMessage::~WhiteboardMessage() {
  // @@protoc_insertion_point(destructor:whiteboard.WhiteboardMessage)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void WhiteboardMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.header_;
  if (this != internal_default_instance()) delete _impl_.meta_;
  if (has_data()) {
    clear_data();
  }
}

void WhiteboardMessage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void WhiteboardMessage::clear_data() {
// @@protoc_insertion_point(one_of_clear_start:whiteboard.WhiteboardMessage)
  switch (data_case()) {
    case kRoomData: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.data_.room_data_;
      }
      break;
    }
    case kDrawData: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.data_.draw_data_;
      }
      break;
    }
    case DATA_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = DATA_NOT_SET;
}


void WhiteboardMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:whiteboard.WhiteboardMessage)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.header_ != nullptr) {
    delete _impl_.header_;
  }
  _impl_.header_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.meta_ != nullptr) {
    delete _impl_.meta_;
  }
  _impl_.meta_ = nullptr;
  clear_data();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* WhiteboardMessage::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .whiteboard.MessageHeader header = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_header(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .whiteboard.MessageMeta meta = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_meta(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .whiteboard.RoomOperateData room_data = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_room_data(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .whiteboard.DrawOperateData draw_data = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_draw_data(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* WhiteboardMessage::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:whiteboard.WhiteboardMessage)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .whiteboard.MessageHeader header = 1;
  if (this->_internal_has_header()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::header(this),
        _Internal::header(this).GetCachedSize(), target, stream);
  }

  // .whiteboard.MessageMeta meta = 2;
  if (this->_internal_has_meta()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::meta(this),
        _Internal::meta(this).GetCachedSize(), target, stream);
  }

  // .whiteboard.RoomOperateData room_data = 3;
  if (_internal_has_room_data()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::room_data(this),
        _Internal::room_data(this).GetCachedSize(), target, stream);
  }

  // .whiteboard.DrawOperateData draw_data = 4;
  if (_internal_has_draw_data()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::draw_data(this),
        _Internal::draw_data(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:whiteboard.WhiteboardMessage)
  return target;
}

size_t WhiteboardMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:whiteboard.WhiteboardMessage)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .whiteboard.MessageHeader header = 1;
  if (this->_internal_has_header()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.header_);
  }

  // .whiteboard.MessageMeta meta = 2;
  if (this->_internal_has_meta()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.meta_);
  }

  switch (data_case()) {
    // .whiteboard.RoomOperateData room_data = 3;
    case kRoomData: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.data_.room_data_);
      break;
    }
    // .whiteboard.DrawOperateData draw_data = 4;
    case kDrawData: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.data_.draw_data_);
      break;
    }
    case DATA_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData WhiteboardMessage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    WhiteboardMessage::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*WhiteboardMessage::GetClassData() const { return &_class_data_; }


void WhiteboardMessage::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<WhiteboardMessage*>(&to_msg);
  auto& from = static_cast<const WhiteboardMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:whiteboard.WhiteboardMessage)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_header()) {
    _this->_internal_mutable_header()->::whiteboard::MessageHeader::MergeFrom(
        from._internal_header());
  }
  if (from._internal_has_meta()) {
    _this->_internal_mutable_meta()->::whiteboard::MessageMeta::MergeFrom(
        from._internal_meta());
  }
  switch (from.data_case()) {
    case kRoomData: {
      _this->_internal_mutable_room_data()->::whiteboard::RoomOperateData::MergeFrom(
          from._internal_room_data());
      break;
    }
    case kDrawData: {
      _this->_internal_mutable_draw_data()->::whiteboard::DrawOperateData::MergeFrom(
          from._internal_draw_data());
      break;
    }
    case DATA_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void WhiteboardMessage::CopyFrom(const WhiteboardMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:whiteboard.WhiteboardMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WhiteboardMessage::IsInitialized() const {
  return true;
}

void WhiteboardMessage::InternalSwap(WhiteboardMessage* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(WhiteboardMessage, _impl_.meta_)
      + sizeof(WhiteboardMessage::_impl_.meta_)
      - PROTOBUF_FIELD_OFFSET(WhiteboardMessage, _impl_.header_)>(
          reinterpret_cast<char*>(&_impl_.header_),
          reinterpret_cast<char*>(&other->_impl_.header_));
  swap(_impl_.data_, other->_impl_.data_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata WhiteboardMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_white_5fboard_2eproto_getter, &descriptor_table_white_5fboard_2eproto_once,
      file_level_metadata_white_5fboard_2eproto[4]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace whiteboard
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::whiteboard::MessageHeader*
Arena::CreateMaybeMessage< ::whiteboard::MessageHeader >(Arena* arena) {
  return Arena::CreateMessageInternal< ::whiteboard::MessageHeader >(arena);
}
template<> PROTOBUF_NOINLINE ::whiteboard::MessageMeta*
Arena::CreateMaybeMessage< ::whiteboard::MessageMeta >(Arena* arena) {
  return Arena::CreateMessageInternal< ::whiteboard::MessageMeta >(arena);
}
template<> PROTOBUF_NOINLINE ::whiteboard::RoomOperateData*
Arena::CreateMaybeMessage< ::whiteboard::RoomOperateData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::whiteboard::RoomOperateData >(arena);
}
template<> PROTOBUF_NOINLINE ::whiteboard::DrawOperateData*
Arena::CreateMaybeMessage< ::whiteboard::DrawOperateData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::whiteboard::DrawOperateData >(arena);
}
template<> PROTOBUF_NOINLINE ::whiteboard::WhiteboardMessage*
Arena::CreateMaybeMessage< ::whiteboard::WhiteboardMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::whiteboard::WhiteboardMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
